### ISSUE TITLE
UnhandledPromiseRejectionWarning: DBusError: Failed to activate service 'org.bluez': timed out 

### ISSUE THREAD

**Issue by zissou1** [icanos/hassio-plejd#107]
Hello, what am I doing wrong? The plead units are found but when I try to turn one on or off I get an "UnhandledPromiseRejectionWarning: DBusError: Failed to activate service 'org.bluez': timed out ".
Running fresh install of Home assistant on an RPI 3B (or +).

plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (DIM-01) named Köksbänken with PID 11.
plejd-mqtt: discovered light (CTR-01) named Fönster 1 with PID 16.
plejd-mqtt: discovered light (CTR-01) named Fönster 2 with PID 17.
plejd-mqtt: discovered light (DIM-02) named Köksön with PID 19.
plejd-mqtt: discovered light (DIM-02) named Kök spotlights with PID 20.
plejd-mqtt: discovered light (DIM-02) named Matrummet with PID 22.
plejd-mqtt: discovered light (DIM-02) named Matbordet with PID 23.
plejd-mqtt: discovered switch (Scene) named God natt with PID 3.
plejd-mqtt: discovered switch (Scene) named Dagsbelysning with PID 5.
plejd-mqtt: discovered switch (Scene) named Mysbelysning with PID 2.
(node:292) UnhandledPromiseRejectionWarning: DBusError: Failed to activate service 'org.bluez': timed out (service_start_timeout=25000ms)
    at _methodReturnHandlers.(anonymous function) (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:555:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:292) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:292) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by zissou1** [comment]
Solved it by buying a rpi4
