### ISSUE TITLE
UnhandledPromiseRejectionWarning: DBusError: Failed to activate service 'org.bluez': timed out

### ISSUE THREAD

**Issue by Mikro007** [icanos/hassio-plejd#108]
`(node:294) UnhandledPromiseRejectionWarning: DBusError: Failed to activate service 'org.bluez': timed out (service_start_timeout=25000ms)
    at _methodReturnHandlers.(anonymous function) (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:555:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:294) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:294) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Edit: This came after latest update of HA and I tried to reboot but it´s not working at all :(
I got this on my Rpi 3 b+???

**Comment by Mikro007** [comment]
This is Rpi 3 b+ related. I did same process on my Rpi 4 with no problem.

**Comment by icanos** [comment]
Adding info to the README that RPi 3b+ isn't supported. Thanks for the feedback.
