### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined  at PlejdApi.getDevices

### ISSUE THREAD

**Issue by allefralle** [icanos/hassio-plejd#151]
Hi 

Im having problem with the plejd adon. I have installed it trough the Supervisor and it workt fine. Unfortunate im getting the 403 error that im unable to retrieve session token response:  

2021-01-23 21:15:59Z ERR plejd-api Unable to retrieve session token response: Error: Request failed with status code 403
(node:15150) UnhandledPromiseRejectionWarning: unable to retrieve session token response: Error: Request failed with status code 403

But not allways, after a reboot i get below error instead. Mostly i get below error once and then i get the 403 error instead. 

starting Plejd add-on v. 0.4.8
2021-01-23 23:45:16Z INF plejd-api login()
2021-01-23 23:45:16Z INF plejd-api logging into Puerto
2021-01-23 23:45:17Z INF plejd-api got session token response
2021-01-23 23:45:17Z INF plejd-api getSites()
2021-01-23 23:45:17Z INF plejd-api got site list response
2021-01-23 23:45:17Z INF plejd-api getSite(...)
2021-01-23 23:45:18Z INF plejd-api got site details response
(node:641) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined
    at PlejdApi.getDevices (/plejd/api.js:266:41)
    at /plejd/main.js:28:34
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

So i manneged to logg in i guess but something goes wrong. 

Im running Home Assistant 2021.1.4 on a rpi4-64 and Plejd (0.4.8). 

Copy of config:
site: PlejdSite
username: plejduser@mail.com
password: passplejd
mqttBroker: 'mqtt://192.168.6.62:1883'
mqttUsername: mqtuser
mqttPassword: mqtpass
includeRoomsAsLights: false
connectionTimeout: 2
writeQueueWaitTime: 400

Copy of conficuration.yaml
mqtt:
  broker: 192.168.6.62:1883
  username: mqtuser
  password: mqtpass
  discovery: true
  discovery_prefix: homeassistant
  birth_message: 
    topic: 'hass/status'
    payload: 'online'
  will_message: 
    topic: 'hass/status'
    payload: 'offline'

Would love to use Plejd together with Home Assistant. So thanks in advance for any help!

**Comment by allefralle** [comment]
Solved by deleting rooms without lamps in Plejd app.
