### ISSUE TITLE
[plejd-ble] Unable to connect.  Software caused connection abort

### ISSUE THREAD

**Issue by pmikal** [icanos/hassio-plejd#173]
Hello!

I'm running a Home Assistant Blue! First time running and haven't been able to control my Plejd device. Configuration seems to have gone correctly, device is discovered, no error messages with debug logging. Light shows up in dashboard, but when I attempt to control it, an error shows up and nothing happens. Relevant part of the logs:

2021-03-14 13:24:02 INF [plejd-ble] init()
2021-03-14 13:24:02 DBG [plejd-ble] Found BLE interface 'org.bluez.Adapter1' at /org/bluez/hci0
2021-03-14 13:24:03 INF [plejd-ble] BLE init done, waiting for devices.
2021-03-14 13:24:03 DBG [plejd-ble] Found Plejd service on /org/bluez/hci0/dev_C4_0E_83_05_02_2C
2021-03-14 13:24:03 DBG [plejd-ble] initDiscoveredPlejdDevice(). Got /org/bluez/hci0/dev_C4_0E_83_05_02_2C device
2021-03-14 13:24:03 DBG [plejd-ble] Inspecting /org/bluez/hci0/dev_C4_0E_83_05_02_2C
2021-03-14 13:24:03 DBG [plejd-ble] Discovered /org/bluez/hci0/dev_C4_0E_83_05_02_2C with rssi -76, name Taklampa
2021-03-14 13:24:05 INF [plejd-ble] Device discovery done, found 1 Plejd devices
2021-03-14 13:24:05 INF [plejd-ble] Connecting to /org/bluez/hci0/dev_C4_0E_83_05_02_2C
2021-03-14 13:24:09 INF [plejd-ble] Plejd got turn on command for Taklampa (11), brightness undefined
2021-03-14 13:24:09 DBG [plejd-ble] Queueing turn on Taklampa (11). No brightness specified, setting DIM to previous.
2021-03-14 13:24:17 WRN [plejd-ble] Unable to connect.  Software caused connection abort
DBusError: Software caused connection abort
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:337:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:96:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:146:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2021-03-14 13:24:17 ERR [plejd-ble] Could not connect to any Plejd device. Starting reconnect loop...
2021-03-14 13:24:17 DBG [plejd-ble] Starting reconnect loop due to Could not connect to any Plejd device

Any ideas?

**Comment by SweVictor** [comment]
I got that ("software ...") A LOT when the BLE adapter was a bit too far away from the Plejd device. It typically started working after many attempts though (it should retry). You could try increasing the connection timeout in the settings otherwise it's hard to know. Follow the readme, shut down addon, turn off/on the adapter with `bluetoothctl`, restart addon and hope for the best maybe?

**Comment by pmikal** [comment]
@SweVictor - thank you so much! I moved my HA Blue next to the Plejd device and it worked perfectly. (For anyone else with this issue, changing the timeout settings or any of the other troubleshooting tips did nothing to help. )

This device was getting in the -70 rssi range, which I thought would have been an acceptable signal strength for making a connection, but I guess not. Only two rooms away. :( How do people reliably connect to a full home of Plejd devices? Would a long range bluetooth adaptor be enough for reliable coverage?

**Comment by SweVictor** [comment]
This addon (and the Plejd app and Gateway) only connects to one Plejd device. From there the internal Plejd mesh will route the commands data to the correct device. So - as long as you have "enough" Plejd devices in your home you shouldn't have any problems. 

The note about RSSI is interesting - what kind of signal strength are you getting now?

**Comment by pmikal** [comment]
Thanks - makes sense. 

RSSI is now -40, so fairly strong.

**Comment by SweVictor** [comment]
Ok, thanks for reporting back. I'll add a note in the troubleshooting section for upcoming releases.
