### ISSUE TITLE
Can't connect to device: TypeError: Cannot read property 'dimmable'

### ISSUE THREAD

**Issue by waroen** [icanos/hassio-plejd#175]
2021-03-24 14:26:32 INF [plejd-api] Getting devices from site details response...
Catastrophic error. Resetting entire addon in 1 minute TypeError: Cannot read property 'dimmable' of undefined
    at /plejd/PlejdApi.js:338:88
    at Array.some (<anonymous>)
    at /plejd/PlejdApi.js:338:30
    at Array.forEach (<anonymous>)
    at PlejdApi._getRoomDevices (/plejd/PlejdApi.js:331:30)
    at PlejdApi.getDevices (/plejd/PlejdApi.js:198:10)
    at PlejdApi.init (/plejd/PlejdApi.js:64:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async PlejdAddon.init (/plejd/PlejdAddon.js:45:5)

**Comment by SweVictor** [comment]
What version are you running?

**Comment by waroen** [comment]
0.7.0

**Comment by SweVictor** [comment]
Ok, thanks. It seems potentially related to #169, strange though since that should be fixed. Could you try turning off "include rooms as devices" if you have it on?

**Comment by waroen** [comment]
Turning that off fixed it.

**Comment by seranoo** [comment]
Turning off "includeRoomsAsLights" solved it for me.

**Comment by SweVictor** [comment]
Core problem fixed in develop branch, will be released shortly as 0.7.1
