### ISSUE TITLE
Discovery finds lights but claims not to

### ISSUE THREAD

**Issue by mar-schmidt** [icanos/hassio-plejd#182]
Tested with hass core 2021.3.4 and 2021.4.0

Log output:
```
2021-04-07 22:27:46 INF [plejd-mqtt] Discovered light (DIM-01) named Takuttag matsal högadelen with PID 42.
2021-04-07 22:27:46 DBG [plejd-mqtt] Sending discovery for Takuttag allrum våning 2
2021-04-07 22:27:46 INF [plejd-mqtt] Discovered light (DIM-02) named Takuttag allrum våning 2 with PID 43.
2021-04-07 22:27:46 DBG [plejd-mqtt] Sending discovery for Takuttag tvättrum
2021-04-07 22:27:46 INF [plejd-mqtt] Discovered light (DIM-02) named Takuttag tvättrum with PID 46.
2021-04-07 22:27:46 DBG [plejd-mqtt] Sending discovery for ... 
2021-04-07 22:27:46 INF [plejd-mqtt] Discovered light (DIM-02) named ...  with PID 47.
2021-04-07 22:28:01 ERR [plejd-ble] Discovery timeout elapsed, no devices found. Starting reconnect loop...
2021-04-07 22:28:01 DBG [plejd-ble] Starting reconnect loop due to Discovery timeout elapsed
2021-04-07 22:28:01 INF [plejd-ble] Starting reconnect loop...
2021-04-07 22:28:01 INF [device-comm] Bluetooth reconnecting...
2021-04-07 22:28:06 INF [plejd-ble] Reconnecting BLE...
2021-04-07 22:28:06 INF [plejd-ble] init()
2021-04-07 22:28:06 DBG [plejd-ble] Found BLE interface 'org.bluez.Adapter1' at /org/bluez/hci0
2021-04-07 22:28:11 ERR [plejd-ble] Failed to start discovery. Operation already in progress
DBusError: Operation already in progress
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2021-04-07 22:28:11 INF [plejd-ble] If you continue to get "operation already in progress" error, you can try power cycling the bluetooth adapter. Get root console access, run "bluetoothctl" => "power off" => "power on" => "exit" => restart addon.
2021-04-07 22:28:11 WRN [plejd-ble] Failed reconnecting. Failed to start discovery. Make sure no other add-on is currently scanning.
Error: Failed to start discovery. Make sure no other add-on is currently scanning.
    at PlejBLEHandler._startGetPlejdDevice (/plejd/PlejdBLEHandler.js:428:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-04-07 22:28:11 INF [device-comm] Bluetooth reconnecting...
2021-04-07 22:28:16 INF [plejd-ble] Reconnecting BLE...
2021-04-07 22:28:16 INF [plejd-ble] init()
2021-04-07 22:28:16 DBG [plejd-ble] Found BLE interface 'org.bluez.Adapter1' at /org/bluez/hci0
2021-04-07 22:28:21 ERR [plejd-ble] Discovery timeout elapsed, no devices found. Starting reconnect loop...
2021-04-07 22:28:21 DBG [plejd-ble] Starting reconnect loop due to Discovery timeout elapsed
2021-04-07 22:28:21 INF [plejd-ble] Starting reconnect loop...
2021-04-07 22:28:21 DBG [plejd-ble] Reconnect already in progress. Skipping this call.
2021-04-07 22:28:21 ERR [plejd-ble] Failed to start discovery. Operation already in progress
DBusError: Operation already in progress
```

**Comment by SweVictor** [comment]
You could potentially get some more info by enabling verbose logging.

From the log it seems like what is "discovered" is devices from the Plejd web API and sent via [plejd-mqtt]. The BLE mesh seems to not connect at all. 

Before v0.7.0 the entire addon tended to crash resetting everything. You can manually restart the addon to "try again", but in general the BLE discovery has not been changed. You could try extending the connection timeout and/or moving the adapter closer to the Plejd device if possible.

Hope this helps

**Comment by mar-schmidt** [comment]
thanks for rapid response, I'll look into your suggestions! 🥇

**Comment by mar-schmidt** [comment]
turned out to be an issue with my bluetooth device. Thanks again.

**Comment by SweVictor** [comment]
No worries. I'll look into possibly clarifying logging. I was myself fooled early on by mqtt "discovering" devices.
