### ISSUE TITLE
CTR-01 not switching

### ISSUE THREAD

**Issue by FlyHigh-Swe** [icanos/hassio-plejd#196]
I have a setup with some CTR-01 and REL-02, Most of the time it works fine but sometimes the CTR-01 stops accepting commands while all REL-02 works as they should.

I am running hassio on a RPI4.
I have a ctr that dont respond between 2 rel-2 that responds so I don't think its distance related. 

After a reboot it works fine (I dont recall if its just restarting the host or the actual hardware)
I can see some differences between the REL-02 and the CTR in the log
Here is the start in Debug mode:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Plejd
 Adds support for the Swedish home automation devices from Plejd.
-----------------------------------------------------------
 Add-on version: 0.7.1
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[14:45:41] ERROR: Unknown HTTP error occured
 System:   (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.5.1
 Home Assistant Supervisor: 2021.04.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:45:42] INFO: Starting the Plejd service...
[14:45:42] INFO: Verified permissions on startup script
[14:45:42] INFO: Executing startup script
[14:45:43] INFO: Running add-on
Config: {
  site: 'Valborgsmässogatan 14',
  username: '---scrubbed---',
  password: '---scrubbed---',
  mqttBroker: 'mqtt://',
  mqttUsername: 'mqqt-admin',
  mqttPassword: '---scrubbed---',
  includeRoomsAsLights: false,
  preferCachedApiResponse: false,
  updatePlejdClock: false,
  logLevel: 'debug',
  connectionTimeout: 10,
  writeQueueWaitTime: 500
}

and this is where the problem can be seen (in silly mode) Rel-02 responding correct while CTR-01 isnt switching.

2021-05-14 14:17:02 DBG [plejd-ble] Found BLE interface 'org.bluez.Adapter1' at /org/bluez/hci0
2021-05-14 14:17:02 VRB [plejd-ble] Powering on BLE adapter and waiting 5 seconds
2021-05-14 14:17:02 INF [plejd-mqtt] Connected to MQTT.
2021-05-14 14:17:03 VRB [plejd-main] connected to mqtt.
2021-05-14 14:17:03 DBG [plejd-mqtt] Sending discovery of 10 device(s).
2021-05-14 14:17:03 DBG [plejd-mqtt] Sending discovery for Sparklådebelysning
2021-05-14 14:17:03 INF [plejd-mqtt] Discovered light (CTR-01) named Sparklådebelysning with PID 11.
2021-05-14 14:17:03 DBG [plejd-mqtt] Sending discovery for Poolpump
2021-05-14 14:17:03 INF [plejd-mqtt] Discovered light (CTR-01) named Poolpump with PID 13.
2021-05-14 14:17:03 DBG [plejd-mqtt] Sending discovery for Pool Lampa
2021-05-14 14:17:03 INF [plejd-mqtt] Discovered light (CTR-01) named Pool Lampa with PID 15.
2021-05-14 14:17:03 DBG [plejd-mqtt] Sending discovery for Garage allmänt
2021-05-14 14:17:03 INF [plejd-mqtt] Discovered switch (REL-02) named Garage allmänt with PID 16.
2021-05-14 14:17:03 DBG [plejd-mqtt] Sending discovery for Garage bänk
2021-05-14 14:17:03 INF [plejd-mqtt] Discovered switch (REL-02) named Garage bänk with PID 17.
2021-05-14 14:17:03 DBG [plejd-mqtt] Sending discovery for Utebel. Kväll
2021-05-14 14:17:03 INF [plejd-mqtt] Discovered switch (REL-02) named Utebel. Kväll with PID 19.
2021-05-14 14:17:03 DBG [plejd-mqtt] Sending discovery for Utebel. Natt
2021-05-14 14:17:03 INF [plejd-mqtt] Discovered switch (REL-02) named Utebel. Natt with PID 20.
2021-05-14 14:17:03 DBG [plejd-mqtt] Sending discovery for Ute bel natt paus pannrum
2021-05-14 14:17:03 INF [plejd-mqtt] Discovered switch (REL-02) named Ute bel natt paus pannrum with PID 22.
2021-05-14 14:17:03 DBG [plejd-mqtt] Sending discovery for Ute bel ej paus pannrum
2021-05-14 14:17:03 INF [plejd-mqtt] Discovered switch (REL-02) named Ute bel ej paus pannrum with PID 23.
2021-05-14 14:17:03 DBG [plejd-mqtt] Sending discovery for Test
2021-05-14 14:17:03 INF [plejd-mqtt] Discovered switch (Scene) named Test with PID 1.
2021-05-14 14:17:03 VRB [plejd-mqtt] Sent mqtt config command for light, Sparklådebelysning (11). 
2021-05-14 14:17:03 VRB [plejd-mqtt] Sent mqtt config command for light, Poolpump (13). 
2021-05-14 14:17:03 VRB [plejd-mqtt] Sent mqtt config command for light, Pool Lampa (15). 
2021-05-14 14:17:04 VRB [plejd-mqtt] Sent mqtt config command for switch, Garage allmänt (16). 
2021-05-14 14:17:04 VRB [plejd-mqtt] Sent mqtt config command for switch, Garage bänk (17). 
2021-05-14 14:17:04 VRB [plejd-mqtt] Sent mqtt config command for switch, Utebel. Kväll (19). 
2021-05-14 14:17:04 VRB [plejd-mqtt] Sent mqtt config command for switch, Utebel. Natt (20). 
2021-05-14 14:17:05 VRB [plejd-mqtt] Sent mqtt config command for switch, Ute bel natt paus pannrum (22). 
2021-05-14 14:17:05 VRB [plejd-mqtt] Sent mqtt config command for switch, Ute bel ej paus pannrum (23). 
2021-05-14 14:17:05 VRB [plejd-mqtt] Sent mqtt config command for switch,  (1). 
2021-05-14 14:17:05 VRB [plejd-mqtt] Sent mqtt availability command for light, Sparklådebelysning (11). online
2021-05-14 14:17:05 VRB [plejd-mqtt] Sent mqtt availability command for light, Poolpump (13). online
2021-05-14 14:17:05 VRB [plejd-mqtt] Sent mqtt availability command for light, Pool Lampa (15). online
2021-05-14 14:17:05 VRB [plejd-mqtt] Sent mqtt availability command for switch, Garage allmänt (16). online
2021-05-14 14:17:05 VRB [plejd-mqtt] Sent mqtt availability command for switch, Garage bänk (17). online
2021-05-14 14:17:05 VRB [plejd-mqtt] Sent mqtt availability command for switch, Utebel. Kväll (19). online
2021-05-14 14:17:05 VRB [plejd-mqtt] Sent mqtt availability command for switch, Utebel. Natt (20). online
2021-05-14 14:17:05 VRB [plejd-mqtt] Sent mqtt availability command for switch, Ute bel natt paus pannrum (22). online
2021-05-14 14:17:05 VRB [plejd-mqtt] Sent mqtt availability command for switch, Ute bel ej paus pannrum (23). online
2021-05-14 14:17:05 VRB [plejd-mqtt] Sent mqtt availability command for switch,  (1). online
2021-05-14 14:17:07 VRB [plejd-ble] Iterating 32 BLE managedObjects looking for org.bluez.Device1
2021-05-14 14:17:07 VRB [plejd-ble] Found /org/bluez/hci0/dev_D2_B6_3B_C9_6C_D3
2021-05-14 14:17:07 INF [plejd-ble] disconnecting /org/bluez/hci0/dev_D2_B6_3B_C9_6C_D3. This can take up to 180 seconds
2021-05-14 14:35:37 VRB [plejd-mqtt] Got mqtt SET command for switch, Garage bänk (17): ON
2021-05-14 14:35:37 VRB [plejd-mqtt] Updating state for Garage bänk: 1
2021-05-14 14:35:37 INF [device-comm] Plejd got turn on command for Garage bänk (17), brightness undefined
2021-05-14 14:35:37 DBG [device-comm] Queueing turn on Garage bänk (17). No brightness specified, setting DIM to previous.
2021-05-14 14:35:37 VRB [plejd-mqtt] Sent mqtt state command for switch, Garage bänk (17). 
2021-05-14 14:35:37 VRB [plejd-mqtt] Sent mqtt availability command for switch, Garage bänk (17). online
2021-05-14 14:35:39 VRB [plejd-mqtt] Got mqtt SET command for switch, Garage bänk (17): OFF
2021-05-14 14:35:39 VRB [plejd-mqtt] Updating state for Garage bänk: 0
2021-05-14 14:35:39 INF [device-comm] Plejd got turn off command for Garage bänk (17)
2021-05-14 14:35:39 DBG [device-comm] Queueing turn off 17
2021-05-14 14:35:39 VRB [plejd-mqtt] Sent mqtt state command for switch, Garage bänk (17). 
2021-05-14 14:35:39 VRB [plejd-mqtt] Sent mqtt availability command for switch, Garage bänk (17). online
2021-05-14 14:36:48 VRB [plejd-mqtt] Got mqtt SET command for light, Poolpump (13): {"state": "OFF"}
2021-05-14 14:36:48 INF [device-comm] Plejd got turn off command for Poolpump (13)
2021-05-14 14:36:48 DBG [device-comm] Queueing turn off 13

**Comment by SweVictor** [comment]
So - the log indicates the BLE connection is not up.

`plejd-ble] disconnecting /org/bluez/hci0/dev_D2_B6_3B_C9_6C_D3. This can take up to 180 seconds` 

does not look like a happy last BLE log. It presumably retries many times after this?

**Comment by FlyHigh-Swe** [comment]
I can switch a REL-02 device on and off without problem when this happens, it only seems to affect CTR-01 (I dont have any DIM in the system). What I have seen there are no retries after the Queueing command.

This is the second time i have noticed this issue. The first time I did some more testing but forgot to copy the log before restarting, What I noticed then was that when I toggles a CTR I never saw the  sent and got mqqt-commands in the logs, If I toggled a REL after that the sent and got mqqt lines was generated. I tied to alternate between the devices and the pattern was the same, REL generated the mqqt lines while CTR didnt.

If I see the issue again I will generate a more clear log, sorry for not doing it this time.

**Comment by FlyHigh-Swe** [comment]
Yesterday I noticed that the 3 CTR units shows up in the mqqt integration as devices/ententes while none of the Rel 02 dont. Maybe this is by design but it it still those devices that fail.

**Comment by SweVictor** [comment]
v0.8.0-beta is out now, please have a look if problem persists

**Comment by Mikro007** [comment]
Just updated my hassio to latest 2021.6.4 and now plejd stopped working. I also have v0.8.0-beta.

`2021-06-14 17:59:45 VRB [plejd-mqtt] Sent mqtt config command for scene, Tänd (2dff2fa9-dadb-4615-bbe8-f70ae0efb08c). 
2021-06-14 17:59:45 VRB [plejd-mqtt] Received mqtt message on homeassistant/device_automation/plejd/2dff2fa9-dadb-4615-bbe8-f70ae0efb08c_trig/config
2021-06-14 17:59:45 VRB [plejd-mqtt] Getting device 2dff2fa9-dadb-4615-bbe8-f70ae0efb08c_trig from registry
2021-06-14 17:59:45 VRB [plejd-mqtt] Sent mqtt config command for device_automation,  (2dff2fa9-dadb-4615-bbe8-f70ae0efb08c_trig). 
2021-06-14 17:59:45 VRB [plejd-mqtt] Received mqtt message on homeassistant/scene/plejd/417b2d17-2a01-4032-b43a-8978e081bab9/config
2021-06-14 17:59:45 VRB [plejd-mqtt] Getting scene 417b2d17-2a01-4032-b43a-8978e081bab9 from registry
2021-06-14 17:59:45 VRB [plejd-mqtt] Sent mqtt config command for scene, Släck (417b2d17-2a01-4032-b43a-8978e081bab9). 
2021-06-14 17:59:45 VRB [plejd-mqtt] Received mqtt message on homeassistant/device_automation/plejd/417b2d17-2a01-4032-b43a-8978e081bab9_trig/config
2021-06-14 17:59:45 VRB [plejd-mqtt] Getting device 417b2d17-2a01-4032-b43a-8978e081bab9_trig from registry
2021-06-14 17:59:45 VRB [plejd-mqtt] Sent mqtt config command for device_automation,  (417b2d17-2a01-4032-b43a-8978e081bab9_trig). 
2021-06-14 17:59:47 VRB [plejd-mqtt] Received mqtt message on homeassistant/light/plejd/C4EA30D31AC1_0/availability
2021-06-14 17:59:47 VRB [plejd-mqtt] Getting device C4EA30D31AC1_0 from registry
2021-06-14 17:59:47 VRB [plejd-mqtt] Sent mqtt availability command for light, Taklampa hall (C4EA30D31AC1_0). online
2021-06-14 17:59:47 VRB [plejd-mqtt] Received mqtt message on homeassistant/light/plejd/F9A3975F4EF8_0/availability
2021-06-14 17:59:47 VRB [plejd-mqtt] Getting device F9A3975F4EF8_0 from registry
2021-06-14 17:59:47 VRB [plejd-mqtt] Sent mqtt availability command for light, Bänkbelysning (F9A3975F4EF8_0). online
2021-06-14 17:59:47 VRB [plejd-mqtt] Received mqtt message on homeassistant/light/plejd/D95E5EDFB3D2_0/availability
2021-06-14 17:59:47 VRB [plejd-mqtt] Getting device D95E5EDFB3D2_0 from registry
2021-06-14 17:59:47 VRB [plejd-mqtt] Sent mqtt availability command for light, Köksbord (D95E5EDFB3D2_0). online
2021-06-14 17:59:47 VRB [plejd-mqtt] Received mqtt message on homeassistant/light/plejd/CF55AEDD43E4_0/availability
2021-06-14 17:59:47 VRB [plejd-mqtt] Getting device CF55AEDD43E4_0 from registry
2021-06-14 17:59:47 VRB [plejd-mqtt] Sent mqtt availability command for light, Taklampa allrum (CF55AEDD43E4_0). online
2021-06-14 17:59:47 VRB [plejd-mqtt] Received mqtt message on homeassistant/light/plejd/C1729049EB4B_0/availability
2021-06-14 17:59:47 VRB [plejd-mqtt] Getting device C1729049EB4B_0 from registry
2021-06-14 17:59:47 VRB [plejd-mqtt] Sent mqtt availability command for light, Taklampa kök (C1729049EB4B_0). online
2021-06-14 17:59:47 VRB [plejd-mqtt] Received mqtt message on homeassistant/light/plejd/DA4ABBBDD7B3_0/availability
2021-06-14 17:59:47 VRB [plejd-mqtt] Getting device DA4ABBBDD7B3_0 from registry
2021-06-14 17:59:47 VRB [plejd-mqtt] Sent mqtt availability command for light, Soffbord (DA4ABBBDD7B3_0). online
2021-06-14 17:59:47 VRB [plejd-mqtt] Received mqtt message on homeassistant/light/plejd/D1F037ABCF90_0/availability
2021-06-14 17:59:47 VRB [plejd-mqtt] Getting device D1F037ABCF90_0 from registry
2021-06-14 17:59:47 VRB [plejd-mqtt] Sent mqtt availability command for light, Hall Groventré (D1F037ABCF90_0). online
2021-06-14 17:59:47 VRB [plejd-mqtt] Received mqtt message on homeassistant/light/plejd/F88E5274E2B3_0/availability
2021-06-14 17:59:47 VRB [plejd-mqtt] Getting device F88E5274E2B3_0 from registry
2021-06-14 17:59:47 VRB [plejd-mqtt] Sent mqtt availability command for light, Taklampa sovrum (F88E5274E2B3_0). online
2021-06-14 17:59:47 VRB [plejd-mqtt] Received mqtt message on homeassistant/light/plejd/EFCEB3FAC37B_0/availability
2021-06-14 17:59:47 VRB [plejd-mqtt] Getting device EFCEB3FAC37B_0 from registry
2021-06-14 17:59:47 VRB [plejd-mqtt] Sent mqtt availability command for light, Vitrinskåp (EFCEB3FAC37B_0). online
2021-06-14 17:59:47 VRB [plejd-mqtt] Received mqtt message on homeassistant/light/plejd/C46014B1A54D_0/availability
2021-06-14 17:59:47 VRB [plejd-mqtt] Getting device C46014B1A54D_0 from registry
2021-06-14 17:59:47 VRB [plejd-mqtt] Sent mqtt availability command for light, Taklampa barnrum (C46014B1A54D_0). online
2021-06-14 17:59:47 VRB [plejd-mqtt] Received mqtt message on homeassistant/light/plejd/FC4D45E40C3A_0/availability
2021-06-14 17:59:47 VRB [plejd-mqtt] Getting device FC4D45E40C3A_0 from registry
2021-06-14 17:59:47 VRB [plejd-mqtt] Sent mqtt availability command for light, Hall entré (FC4D45E40C3A_0). online
2021-06-14 17:59:47 VRB [plejd-mqtt] Received mqtt message on homeassistant/light/plejd/CBA4569C068E_0/availability
2021-06-14 17:59:47 VRB [plejd-mqtt] Getting device CBA4569C068E_0 from registry
2021-06-14 17:59:47 VRB [plejd-mqtt] Sent mqtt availability command for light, Taklampa entre (CBA4569C068E_0). online
2021-06-14 17:59:47 VRB [plejd-mqtt] Received mqtt message on homeassistant/light/plejd/EF5CB366811C_0/availability
2021-06-14 17:59:47 VRB [plejd-mqtt] Getting device EF5CB366811C_0 from registry
2021-06-14 17:59:47 VRB [plejd-mqtt] Sent mqtt availability command for light, Wc (EF5CB366811C_0). online
2021-06-14 17:59:47 VRB [plejd-mqtt] Received mqtt message on homeassistant/light/plejd/C681D1584836_0/availability
2021-06-14 17:59:47 VRB [plejd-mqtt] Getting device C681D1584836_0 from registry
2021-06-14 17:59:47 VRB [plejd-mqtt] Sent mqtt availability command for light, Taklampa badrum (C681D1584836_0). online
2021-06-14 17:59:47 VRB [plejd-mqtt] Received mqtt message on homeassistant/scene/plejd/2dff2fa9-dadb-4615-bbe8-f70ae0efb08c/availability
2021-06-14 17:59:47 VRB [plejd-mqtt] Getting scene 2dff2fa9-dadb-4615-bbe8-f70ae0efb08c from registry
2021-06-14 17:59:47 VRB [plejd-mqtt] Sent mqtt availability command for scene, Tänd (2dff2fa9-dadb-4615-bbe8-f70ae0efb08c). online
2021-06-14 17:59:47 VRB [plejd-mqtt] Received mqtt message on homeassistant/scene/plejd/417b2d17-2a01-4032-b43a-8978e081bab9/availability
2021-06-14 17:59:47 VRB [plejd-mqtt] Getting scene 417b2d17-2a01-4032-b43a-8978e081bab9 from registry
2021-06-14 17:59:47 VRB [plejd-mqtt] Sent mqtt availability command for scene, Släck (417b2d17-2a01-4032-b43a-8978e081bab9). online
2021-06-14 17:59:50 VRB [plejd-ble] Iterating 32 BLE managedObjects looking for org.bluez.Device1
2021-06-14 17:59:50 VRB [plejd-ble] Found /org/bluez/hci0/dev_C3_6C_77_18_10_BE
2021-06-14 17:59:50 INF [plejd-ble] disconnecting /org/bluez/hci0/dev_C3_6C_77_18_10_BE. This can take up to 180 seconds
2021-06-14 17:59:52 VRB [plejd-ble] Removing /org/bluez/hci0/dev_C3_6C_77_18_10_BE from adapter.
2021-06-14 17:59:52 VRB [plejd-ble] All active BLE device connections cleaned up.
2021-06-14 17:59:52 VRB [plejd-ble] Got adapter undefined
2021-06-14 17:59:52 VRB [plejd-ble] Setting up interfacesAdded subscription and discovery filter
2021-06-14 17:59:52 VRB [plejd-ble] Starting BLE discovery... This can take up to 180 seconds.
2021-06-14 17:59:52 VRB [plejd-ble] Started BLE discovery
2021-06-14 17:59:52 INF [plejd-ble] BLE init done, waiting for devices.
2021-06-14 17:59:52 INF [plejd-main] Main init done
2021-06-14 17:59:52 INF [plejd-main] main() finished
2021-06-14 17:59:52 DBG [plejd-ble] Found Plejd service on /org/bluez/hci0/dev_C0_4F_FA_83_17_D8
2021-06-14 17:59:52 DBG [plejd-ble] initDiscoveredPlejdDevice(). Got /org/bluez/hci0/dev_C0_4F_FA_83_17_D8 device
2021-06-14 17:59:52 DBG [plejd-ble] Inspecting /org/bluez/hci0/dev_C0_4F_FA_83_17_D8
2021-06-14 17:59:52 DBG [plejd-ble] Discovered /org/bluez/hci0/dev_C0_4F_FA_83_17_D8 with rssi -72 dBm, name undefined
2021-06-14 17:59:57 INF [plejd-ble] Device discovery done, found 1 Plejd devices
2021-06-14 17:59:57 VRB [plejd-ble] Inspecting /org/bluez/hci0/dev_C0_4F_FA_83_17_D8
2021-06-14 17:59:57 INF [plejd-ble] Connecting to /org/bluez/hci0/dev_C0_4F_FA_83_17_D8
2021-06-14 18:00:03 WRN [plejd-ble] Unable to connect.  Software caused connection abort
DBusError: Software caused connection abort
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2021-06-14 18:00:03 VRB [plejd-ble] Stopping discovery...
2021-06-14 18:00:03 VRB [plejd-ble] Stopped BLE discovery
2021-06-14 18:00:03 ERR [plejd-ble] Could not connect to any Plejd device. Starting reconnect loop...
2021-06-14 18:00:03 DBG [plejd-ble] Starting reconnect loop due to Could not connect to any Plejd device
2021-06-14 18:00:03 INF [plejd-ble] Starting reconnect loop...
2021-06-14 18:00:03 VRB [plejd-ble] Starting internal reconnect loop...
2021-06-14 18:00:03 VRB [plejd-ble] Reconnect: Clean up, emit reconnect event, wait 5s and the re-init...
2021-06-14 18:00:03 VRB [plejd-ble] cleanup() - Clearing ping interval and clock update timer
2021-06-14 18:00:03 VRB [plejd-ble] Removing listeners to write events, bus events and objectManager...
2021-06-14 18:00:03 VRB [plejd-ble] Reconnect attempt 1 in a row. Will power cycle every 10th time.
2021-06-14 18:00:03 INF [device-comm] Bluetooth reconnecting...
2021-06-14 18:00:03 VRB [device-comm] Stopping writeQueue loop until connection is established. Write queue length: 0`

**Comment by Mikro007** [comment]
No ctr-01 are showing after updated to 0.8.0-beta?

**Comment by SweVictor** [comment]
@Mikro007 I suggest you open a new issue if you have problems. In my installation, several CTR-01 works well after the update. You can check all devices added under Configuration => Integrations => Mqtt => Devices / Entities. If you did not follow the upgrade suggestions you will probably have a lot with "_2" suffix and the "old" ones without suffix will no longer work.

**Comment by FlyHigh-Swe** [comment]
After the update I have not seen this issue,
