### ISSUE TITLE
BLE not connecting

### ISSUE THREAD

**Issue by supersonical** [icanos/hassio-plejd#206]
Running addon version 0.4.7 is working fine but upgrading to the latest beta version or 0.7.1 doesnt work at all. 
My system is HASSOS Version 6 and running on a NUC

Error message follows:

2021-06-19 01:56:18 INF [device-comm] Bluetooth reconnecting...
2021-06-19 01:56:20 ERR [plejd-ble] Discovery timeout elapsed, no devices found. Starting reconnect loop...
2021-06-19 01:56:20 INF [plejd-ble] Starting reconnect loop...
2021-06-19 01:56:23 INF [plejd-ble] Reconnecting BLE...
2021-06-19 01:56:23 INF [plejd-ble] init()
2021-06-19 01:56:29 ERR [plejd-ble] Failed to start discovery. Operation already in progress
DBusError: Operation already in progress
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2021-06-19 01:56:29 INF [plejd-ble] If you continue to get "operation already in progress" error, you can try power cycling the bluetooth adapter. Get root console access, run "bluetoothctl" => "power off" => "power on" => "exit" => restart addon.
2021-06-19 01:56:29 WRN [plejd-ble] Failed reconnecting. Failed to start discovery. Make sure no other add-on is currently scanning.
Error: Failed to start discovery. Make sure no other add-on is currently scanning.
    at PlejBLEHandler._startGetPlejdDevice (/plejd/PlejdBLEHandler.js:428:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-06-19 01:56:29 INF [device-comm] Bluetooth reconnecting...

**Comment by supersonical** [comment]
Looks like the discovery is timing out and says of a couple tries its busy with other adoons. But i have nothing els using BLE or bluetooth.

**Comment by SweVictor** [comment]
I get these quite frequently when connecting. Most often it starts working after _many_ reconnects. If not I typically cold boot (restart) the entire computer to re-initialize the BLE adapter. YMMV

**Comment by supersonical** [comment]
Thank you for answering! Tried that and i have reinstalled the addon plus restarted the host and some other troubleshooting guids. Nothing worked and the only way i got it to work was rolling back the addon to 0.4.7

**Comment by SweVictor** [comment]
Sorry to hear that. It seems like the same underlying BLE lib is used in both versions, so I really don't know what difference downgrading would do. I know the older versions logged a lot less, but if you could post logs from the startup of the working version, maybe we could get something. I'm not that hopeful though unfortunately...
