### ISSUE TITLE
Plejd not connecting to MQTT?

### ISSUE THREAD

**Issue by simonkarrlsson** [icanos/hassio-plejd#209]
Hey, i've just updated the plejd addon and the core. Now i get this in my logs:

2021-06-21 21:20:42 INF [plejd-mqtt] Initializing MQTT connection for Plejd addon
Catastrophic error. Resetting entire addon in 1 minute Error: Missing protocol
    at Object.connect (/plejd/node_modules/mqtt/lib/connect/index.js:71:13)
    at MqttClient.init (/plejd/MqttClient.js:151:24)
    at PlejdAddon.init (/plejd/PlejdAddon.js:124:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/plejd/main.js:18:5)

I have checked my settings and cant seem to find the problem. Anyone having the same problem?

**Comment by SweVictor** [comment]
A quick search says it could be missing the protocol in the settings, could that be the case? It should be for example `mqtt://localhost`, including the `mqtt://` part.

If not, please post versions you're running.

**Comment by simonkarrlsson** [comment]
I had mqtt://localhost and tryed changing to core-mosquitto and none works. Home Assistant 2021.6.6, 0.8.0-beta for plejd and 6.0.1 mqtt.

**Comment by simonkarrlsson** [comment]
Now I've manage to get them to speak but now I get this:

2021-06-25 10:32:55 INF [plejd-main] Log level set to info
Starting Plejd addon and reading configuration...
2021-06-25 10:32:55 INF [plejd-main] Log level set to info
2021-06-25 10:32:55 INF [plejd-main] Plejd add-on, version 0.8.0-beta
2021-06-25 10:32:55 INF [device-comm] Starting Plejd communication handler.
2021-06-25 10:32:55 INF [plejd-ble] Starting Plejd BLE Handler, resetting all device states.
2021-06-25 10:32:55 INF [plejd-main] Main Plejd addon init()...
2021-06-25 10:32:55 INF [plejd-api] init()
2021-06-25 10:32:55 INF [plejd-api] Getting cached api response from disk
2021-06-25 10:32:55 INF [plejd-api] login()
2021-06-25 10:32:55 INF [plejd-api] logging into Hemma
2021-06-25 10:32:56 INF [plejd-api] got session token response
2021-06-25 10:32:56 INF [plejd-api] Get all Plejd sites for account...
2021-06-25 10:32:56 INF [plejd-api] Got site list response with 1: Hemma
2021-06-25 10:32:56 INF [plejd-api] Site found matching configuration name Hemma
2021-06-25 10:32:56 INF [plejd-api] Get site details for 09f1f5bb-bac8-45a9-9b87-b0bb92f85e12...
2021-06-25 10:32:57 INF [plejd-api] got site details response
2021-06-25 10:32:57 INF [plejd-api] Site details for site id 09f1f5bb-bac8-45a9-9b87-b0bb92f85e12 found
2021-06-25 10:32:57 INF [plejd-api] Saving cached copy
2021-06-25 10:32:57 INF [plejd-api] Getting devices from site details response...
2021-06-25 10:32:57 INF [plejd-api] Plejd gateway 'Vid Routern' found on site
2021-06-25 10:32:57 INF [plejd-mqtt] Initializing MQTT connection for Plejd addon
2021-06-25 10:32:57 INF [plejd-ble] init()
2021-06-25 10:33:03 INF [plejd-ble] BLE init done, waiting for devices.
2021-06-25 10:33:03 INF [plejd-main] Main init done
2021-06-25 10:33:03 INF [plejd-main] main() finished
2021-06-25 10:33:03 WRN [plejd-ble] Device registry does not contain device with serial E91127624367
2021-06-25 10:33:05 ERR [plejd-ble] Discovery timeout elapsed, no devices found. Starting reconnect loop...
2021-06-25 10:33:05 INF [plejd-ble] Starting reconnect loop...
2021-06-25 10:33:05 INF [device-comm] Bluetooth reconnecting...
2021-06-25 10:33:10 INF [plejd-ble] Reconnecting BLE...
2021-06-25 10:33:10 INF [plejd-ble] init()
2021-06-25 10:33:15 ERR [plejd-ble] Failed to start discovery. Operation already in progress
DBusError: Operation already in progress
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)

Any clues?

**Comment by SweVictor** [comment]
Well... These seem to be quite common. I don't think that the recent updates should have made this works, though we had one issue the other day which got resolved by backing down to a very old version... 

What you can do is increase the connection timeout in the settings, cold reboot the computer, move the BT stick closer to a Plejd device etc. You can probably see what's happening with the `bluetoothctl` command as well. My view currently is that this is on the hardware side, but there might be more to it of course.

Out of interest, what did you do to make mqtt work? Might be helpful to others.

**Comment by seglaren** [comment]
Same error for me. 
@simonkarrlsson How did you get rid of this?

Catastrophic error. Resetting entire addon in 1 minute Error: Missing protocol
    at Object.connect (/plejd/node_modules/mqtt/lib/connect/index.js:71:13)
    at MqttClient.init (/plejd/MqttClient.js:151:24)
    at PlejdAddon.init (/plejd/PlejdAddon.js:124:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/plejd/main.js:18:5)

**Comment by gartvall** [comment]
I had the same problem, my hostande was core-mosquitto. Changing to mqtt://core-mosquitto in the plejd configuration solved it for me.
