### ISSUE TITLE
Not connecting to mesh

### ISSUE THREAD

**Issue by martach** [icanos/hassio-plejd#21]
Hi! Thank you for your effort in creating a much needed plugin! I have a couple of questions.

1. Is it possible to connect to my Plejd gateway instead of the Bluetooth mesh?

2. After restarting Home assistant, my Plejd devices are unavailable until I restart the Plejd addon (even though it is already started according to Hassio). Is there a simple way around this?

3. My RPi3 running the latest Hassio and Plejd addon sometimes fails to connect to the mesh network. Is this due to my rotary dimmer devices (eb0414bba104 is an RTR-01)? Is there a way around this?

> discovered Spottar nedre badrum with Plejd ID 26.
> discovered Köksbord with Plejd ID 30.
> discovered Kök with Plejd ID 11.
> discovered Köksö with Plejd ID 21.
> discovered hörn kök/lekrum with Plejd ID 31.
> discovered Teve with Plejd ID 34.
> discovered Johans rum with Plejd ID 36.
> discovered Kamin with Plejd ID 33.
> discovered Spottar övre badrum with Plejd ID 16.
> trying to connect to the mesh network.
> error: discovering characteristics timed out. trying next device.
> error: discovering characteristics timed out. trying next device.
> error: discovering characteristics timed out. trying next device.
> noble warning: unknown peripheral eb0414bba104
> error: discovering characteristics timed out. trying next device.
> noble warning: unknown peripheral eb0414bba104
> warning: currently connecting to a device, please wait...
> error: discovering characteristics timed out. trying next device.
> noble warning: unknown peripheral eb0414bba104
> error: reached end of device list. cannot continue.

**Comment by icanos** [comment]
Hi,

1. Currently no, since I don't own a gateway, I can't really test any code where I connect to the gateway instead. So my focus will be gateway-less connection, at least until that changes :-)

2. It seems that you haven't installed Mosquitto add-on which adds an external MQTT gateway (instead of the built-in), or that you maybe missed the Mosquitto configuration in the README. That configuration makes HA send a message once its started, allowing Plejd to discover the devices once again.

3. That is weird though, does it connect at all? How many Plejd devices do you have? Maybe its time to add a configurable amount of time to do the scanning, it looks like it doesn't discover that many devices in the list above.

**Comment by martach** [comment]
Hi,

Thank you for your answers! I do have Mosquitto installed and configured accordingly, but I can check it again. I have 13 Plejd devices in total, including 3 RTR-01 and 1 gateway. It connects more often than not. When it connects, though, it doesn't send any error messages or warnings about unknown peripherals.

**Comment by icanos** [comment]
Did you get it to work? :-)

**Comment by martach** [comment]
I actually didn't mean to close the issue that quickly :)

1. I can understand that adding gateway connectivity will not be fixed for a foreseeable future. 

2. Was resolved after I discovered an error in my mqtt configuration. 

3. Happens rarely - but if it does reoccur I can get back to you.

Thank you!

**Comment by martach** [comment]
I'm afraid problem 3 is still nagging me, even more frequently. The addon often connects to Plejd and works for a couple of hours. Then it will stop working until I restart it, after which it works for a couple of more hours, and so on. I usually restart the addon a couple of times a dag. I have reinstalled the addon with the problem still persisting.

The log is filled with warnings about an unknown peripheral. I have also seen something about maximum number of listeners, but it's difficult to catch, since the unknown peripheral messages flood the log. Therefore, I cannot tell if the problems are connected.

> (node:291) MaxListenersExceededWatning: Possible EventEmitter memory leak detected. 11 write listeners added. Use emitter.setMaxListeners() to increase limit

The unit id sometimes differ, but it's always one unit at a time. Everything works well with buttons and the Plejd app. I usually use the gateway. But even when I forced a connection to a unit mentioned in the log, controlling lights via the plejd app was successful.

> noble warning: unknown peripheral d684f8192d6b
> noble warning: unknown peripheral d684f8192d6b
> noble warning: unknown peripheral d684f8192d6b
> noble warning: unknown peripheral d684f8192d6b
> noble warning: unknown peripheral d684f8192d6b
> noble warning: unknown peripheral d684f8192d6b
> noble warning: unknown peripheral d684f8192d6b
> noble warning: unknown peripheral d684f8192d6b
> noble warning: unknown peripheral d684f8192d6b
> noble warning: unknown peripheral d684f8192d6b

**Comment by icanos** [comment]
I'm currently looking into this, the weird thing is that I've been running the code for 2 weeks now I think and its been rock solid ever since.

**Comment by martach** [comment]
Thank you for looking into this. After the latest update, this is an example of what the log looks like when the addon has stopped working:

> noble warning: unknown peripheral ea5f8abd83de
> /plejd/node_modules/@icanos/noble/lib/hci-socket/bindings.js:380
>     throw new UnknownPeripheralError(uuid);
>                                      ^
> ReferenceError: uuid is not defined
>     at NobleBindings.write (/plejd/node_modules/@icanos/noble/lib/hci-socket/bindings.js:380:38)
>     at Noble.write (/plejd/node_modules/@icanos/noble/lib/noble.js:325:19)
>     at Characteristic.write (/plejd/node_modules/@icanos/noble/lib/characteristic.js:74:15)
>     at PlejdService.write (/plejd/ble.js:311:31)
>     at PlejdService._turnOn (/plejd/ble.js:125:10)
>     at PlejdService.turnOn (/plejd/ble.js:110:12)
>     at MqttClient.client.on (/plejd/main.js:46:17)
>     at MqttClient.emit (events.js:198:13)
>     at MqttClient.client.on (/plejd/mqtt.js:108:14)
>     at MqttClient.emit (events.js:198:13)
> [09:23:04] INFO: Starting the Plejd service...
> [09:23:04] INFO: Verified permissions on startup script
> [09:23:04] INFO: Executing startup script
> [09:23:06] INFO: Wrote plejd.json
> [09:23:07] INFO: Running add-on

**Comment by icanos** [comment]
Please have another try with the latest version, if you're still interested :-)

**Comment by martach** [comment]
Thank you! I haven't yet hade any of the warnings lately, however the plug-in stops responding after some time. In the log I see:

> (node:292) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 write 
> listeners added. Use emitter.setMaxListeners() to increase limit

I see there are other open issues regarding this error. If I don't get any noble warnings for a couple of more days, I can close this issue, and the possible memory leak can be investigated through the other open issues.

**Comment by nixs64** [comment]
I have a similar situation after 0.3.x updates on my Raspberry Pi 3B, wont connect to Plejd mesh at all.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Plejd
 Adds support for the Swedish home automation devices from Plejd.
-----------------------------------------------------------
 Add-on version: 0.3.3
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[11:29:59] ERROR: Unknown HTTP error occured
 System:   (armv7 / raspberrypi3)
 Home Assistant version: 0.104.3
 Supervisor version: 195
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:30:02] INFO: Starting the Plejd service...
[11:30:02] INFO: Verified permissions on startup script
[11:30:02] INFO: Executing startup script
[11:30:04] INFO: Wrote plejd.json
[11:30:04] INFO: Running add-on
starting Plejd add-on v. 0.3.3
plejd-api: login()
plejd-api: logging into Niklas Sjostedt
plejd-api: got session token response
plejd-api: getCryptoKey()
plejd-api: got sites response
wireEvents()
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light named Hanne Alkov with PID 135.
plejd-mqtt: discovered light named Badrum Nere Tak with PID 59.
plejd-mqtt: discovered light named Hanne Tak with PID 143.
plejd-mqtt: discovered light named Korridor Tak with PID 45.
plejd-mqtt: discovered light named Jesper Fönstersmyg  with PID 95.
plejd-mqtt: discovered light named Sovrum Fönstersmyg with PID 81.
plejd-mqtt: discovered light named Köksbord Taklampa  with PID 26.
plejd-mqtt: discovered light named Kontor Tak  with PID 21.
plejd-mqtt: discovered light named Badrum Uppe Tak with PID 126.
plejd-mqtt: discovered light named Jesper Alkov with PID 100.
plejd-mqtt: discovered light named Vardagsrum Uppe Fönstersmyg with PID 91.
plejd-mqtt: discovered light named Utebelysning Veranda with PID 153.
plejd-mqtt: discovered light named Badrum Nere Fönstersmyg  with PID 77.
plejd-mqtt: discovered light named Jesper Tak with PID 113.
plejd-mqtt: discovered light named Kök Tak with PID 40.
plejd-mqtt: discovered light named Badrum Uppe Fönstersmyg  with PID 130.
plejd-mqtt: discovered light named Utebelysning Altandörr Kök with PID 49.
plejd-mqtt: discovered light named Vardagsrum Nere Tak with PID 64.
plejd-mqtt: discovered light named Hall with PID 69.
plejd-mqtt: discovered light named Utebelysning Garage with PID 147.
plejd-mqtt: discovered light named Sovrum with PID 54.
plejd-mqtt: discovered light named Hanne Fönstersmyg with PID 139.
plejd-mqtt: discovered light named Kontor Fönstersmyg with PID 85.
plejd-mqtt: discovered light named Fönstersmyg, Vardagsrum, Hall, Matplats with PID 16.
plejd-mqtt: discovered light named Utebelysning Altandörr Övervåning with PID 117.
plejd-mqtt: discovered light named Utebelysning Källardörr with PID 121.
plejd-mqtt: discovered light named Matplats Tak with PID 30.
plejd-mqtt: discovered light named Kök Vitrinskåp, Överskåp with PID 73.
plejd-mqtt: discovered light named Vardagsrum Uppe Tak with PID 104.
plejd-mqtt: discovered light named Trappa with PID 109.
plejd-mqtt: discovered light named Köksbänk Tak with PID 36.
onDeviceConnected()
plejd-ble: error: unable to connect to the Plejd mesh.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
(node:291) UnhandledPromiseRejectionWarning: DBusError: Operation already in progress
    at _methodReturnHandlers.(anonymous function) (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:55:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:554:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:291) UnhandledPromiseRejectionWarning: DBusError: Operation already in progress
    at _methodReturnHandlers.(anonymous function) (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:55:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:554:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by icanos** [comment]
Can you please restart the addon, does it always give you the "Operation already in progress" error?

**Comment by nixs64** [comment]
Yes, gets same response every time,
Except for one test with rebooted raspberry pi complete

Den lör 25 jan. 2020 11:39Marcus Westin <notifications@github.com> skrev:

**Comment by nixs64** [comment]
This was the response from restart:


[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing...
----------------------------------------------------------- Hass.io
Add-on: Plejd Adds support for the Swedish home automation devices
from Plejd.-----------------------------------------------------------
Add-on version: 0.3.3 You are running the latest version of this
add-on.
parse error: Expected string key before ':' at line 1, column 4
[12:49:33] ERROR: Unknown HTTP error occured System:   (armv7 /
raspberrypi3) Home Assistant version: 0.104.3 Supervisor version:
195----------------------------------------------------------- Please,
share the above information when looking for help or support in, e.g.,
GitHub, forums or the Discord
chat.-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing...
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:49:36] INFO: Starting the Plejd service...
[12:49:36] INFO: Verified permissions on startup script
[12:49:36] INFO: Executing startup script
[12:49:39] INFO: Wrote plejd.json
[12:49:39] INFO: Running add-on
starting Plejd add-on v. 0.3.3
plejd-api: login()
plejd-api: logging into Niklas Sjostedt
plejd-api: got session token response
plejd-api: getCryptoKey()
plejd-api: got sites response
wireEvents()
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light named Hanne Alkov with PID 135.
plejd-mqtt: discovered light named Badrum Nere Tak with PID 59.
plejd-mqtt: discovered light named Hanne Tak with PID 143.
plejd-mqtt: discovered light named Korridor Tak with PID 45.
plejd-mqtt: discovered light named Jesper Fönstersmyg  with PID 95.
plejd-mqtt: discovered light named Sovrum Fönstersmyg with PID 81.
plejd-mqtt: discovered light named Köksbord Taklampa  with PID 26.
plejd-mqtt: discovered light named Kontor Tak  with PID 21.
plejd-mqtt: discovered light named Badrum Uppe Tak with PID 126.
plejd-mqtt: discovered light named Jesper Alkov with PID 100.
plejd-mqtt: discovered light named Vardagsrum Uppe Fönstersmyg with PID 91.
plejd-mqtt: discovered light named Utebelysning Veranda with PID 153.
plejd-mqtt: discovered light named Badrum Nere Fönstersmyg  with PID 77.
plejd-mqtt: discovered light named Jesper Tak with PID 113.
plejd-mqtt: discovered light named Kök Tak with PID 40.
plejd-mqtt: discovered light named Badrum Uppe Fönstersmyg  with PID 130.
plejd-mqtt: discovered light named Utebelysning Altandörr Kök with PID 49.
plejd-mqtt: discovered light named Vardagsrum Nere Tak with PID 64.
plejd-mqtt: discovered light named Hall with PID 69.
plejd-mqtt: discovered light named Utebelysning Garage with PID 147.
plejd-mqtt: discovered light named Sovrum with PID 54.
plejd-mqtt: discovered light named Hanne Fönstersmyg with PID 139.
plejd-mqtt: discovered light named Kontor Fönstersmyg with PID 85.
plejd-mqtt: discovered light named Fönstersmyg, Vardagsrum, Hall,
Matplats with PID 16.
plejd-mqtt: discovered light named Utebelysning Altandörr Övervåning
with PID 117.
plejd-mqtt: discovered light named Utebelysning Källardörr with PID 121.
plejd-mqtt: discovered light named Matplats Tak with PID 30.
plejd-mqtt: discovered light named Kök Vitrinskåp, Överskåp with PID 73.
plejd-mqtt: discovered light named Vardagsrum Uppe Tak with PID 104.
plejd-mqtt: discovered light named Trappa with PID 109.
plejd-mqtt: discovered light named Köksbänk Tak with PID 36.
onDeviceConnected()
plejd-ble: error: unable to connect to the Plejd mesh.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
(node:292) UnhandledPromiseRejectionWarning: DBusError: Operation
already in progress
    at _methodReturnHandlers.(anonymous function)
(/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on
(/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:55:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:554:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:292) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 1)
(node:292) [DEP0018] DeprecationWarning: Unhandled promise rejections
are deprecated. In the future, promise rejections that are not handled
will terminate the Node.js process with a non-zero exit code.
(node:292) UnhandledPromiseRejectionWarning: DBusError: Operation
already in progress
    at _methodReturnHandlers.(anonymous function)
(/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on
(/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:55:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:554:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:292) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 2)


Den lör 25 jan. 2020 12:46Niklas <nixs64@gmail.com> skrev:

**Comment by icanos** [comment]
Have you tried to reboot hass.io?

**Comment by nixs64** [comment]
Yes

Den sön 26 jan. 2020 09:22Marcus Westin <notifications@github.com> skrev:

**Comment by icanos** [comment]
What device are you running?

**Comment by nixs64** [comment]
Raspberry pi 3b


Den mån 27 jan. 2020 11:15Marcus Westin <notifications@github.com> skrev:

**Comment by icanos** [comment]
I've released a new version, 0.3.4. Can you please update to that and set the `connectionTimeout` config parameter to 4?

**Comment by nixs64** [comment]
I will do this later then I get back home.



Den mån 27 jan. 2020 21:48Marcus Westin <notifications@github.com> skrev:

**Comment by nixs64** [comment]
Hello,I updated as suggested and this is the result from today:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing...
----------------------------------------------------------- Hass.io
Add-on: Plejd Adds support for the Swedish home automation devices
from Plejd.-----------------------------------------------------------
Add-on version: 0.3.4 You are running the latest version of this
add-on.
parse error: Expected string key before ':' at line 1, column 4
[19:58:52] ERROR: Unknown HTTP error occured System:   (armv7 /
raspberrypi3) Home Assistant version: 0.104.3 Supervisor version:
195----------------------------------------------------------- Please,
share the above information when looking for help or support in, e.g.,
GitHub, forums or the Discord
chat.-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing...
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:58:55] INFO: Starting the Plejd service...
[19:58:55] INFO: Verified permissions on startup script
[19:58:55] INFO: Executing startup script
[19:58:59] INFO: Wrote plejd.json
[19:58:59] INFO: Running add-on
starting Plejd add-on v. 0.3.4
plejd-api: login()
plejd-api: logging into Niklas Sjostedt
plejd-api: got session token response
plejd-api: getCryptoKey()
plejd-api: got sites response
wireEvents()
init()
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light named Hanne Alkov with PID 135.
plejd-mqtt: discovered light named Badrum Nere Tak with PID 59.
plejd-mqtt: discovered light named Hanne Tak with PID 143.
plejd-mqtt: discovered light named Korridor Tak with PID 45.
plejd-mqtt: discovered light named Jesper Fönstersmyg  with PID 95.
plejd-mqtt: discovered light named Sovrum Fönstersmyg with PID 81.
plejd-mqtt: discovered light named Köksbord Taklampa  with PID 26.
plejd-mqtt: discovered light named Kontor Tak  with PID 21.
plejd-mqtt: discovered light named Badrum Uppe Tak with PID 126.
plejd-mqtt: discovered light named Jesper Alkov with PID 100.
plejd-mqtt: discovered light named Vardagsrum Uppe Fönstersmyg with PID 91.
plejd-mqtt: discovered light named Utebelysning Veranda with PID 153.
plejd-mqtt: discovered light named Badrum Nere Fönstersmyg  with PID 77.
plejd-mqtt: discovered light named Jesper Tak with PID 113.
plejd-mqtt: discovered light named Kök Tak with PID 40.
plejd-mqtt: discovered light named Badrum Uppe Fönstersmyg  with PID 130.
plejd-mqtt: discovered light named Utebelysning Altandörr Kök with PID 49.
plejd-mqtt: discovered light named Vardagsrum Nere Tak with PID 64.
plejd-mqtt: discovered light named Hall with PID 69.
plejd-mqtt: discovered light named Utebelysning Garage with PID 147.
plejd-mqtt: discovered light named Sovrum with PID 54.
plejd-mqtt: discovered light named Hanne Fönstersmyg with PID 139.
plejd-mqtt: discovered light named Kontor Fönstersmyg with PID 85.
plejd-mqtt: discovered light named Fönstersmyg, Vardagsrum, Hall,
Matplats with PID 16.
plejd-mqtt: discovered light named Utebelysning Altandörr Övervåning
with PID 117.
plejd-mqtt: discovered light named Utebelysning Källardörr with PID 121.
plejd-mqtt: discovered light named Matplats Tak with PID 30.
plejd-mqtt: discovered light named Kök Vitrinskåp, Överskåp with PID 73.
plejd-mqtt: discovered light named Vardagsrum Uppe Tak with PID 104.
plejd-mqtt: discovered light named Trappa with PID 109.
plejd-mqtt: discovered light named Köksbänk Tak with PID 36.
onDeviceConnected()
plejd-ble: warning: wasn't able to connect to Plejd, will retry.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
(node:290) UnhandledPromiseRejectionWarning: DBusError: Operation
already in progress
    at _methodReturnHandlers.(anonymous function)
(/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on
(/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:55:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:554:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:290) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 1)
(node:290) [DEP0018] DeprecationWarning: Unhandled promise rejections
are deprecated. In the future, promise rejections that are not handled
will terminate the Node.js process with a non-zero exit code.
init()
plejd-ble: error: failed to start discovery. Make sure no other add-on
is currently scanning.


Den tis 28 jan. 2020 kl 09:30 skrev Niklas <nixs64@gmail.com>:

**Comment by icanos** [comment]
If you’re using a metal case, could you please try to remove that from your Pi and try again?

**Comment by nixs64** [comment]
No metalcase, so not the issue either.

Works for a while after reboot, but stoos respond after some time


Den mån 3 feb. 2020 22:51Marcus Westin <notifications@github.com> skrev:

**Comment by martach** [comment]
I would like to inform you, that after the recent updates and setting the connectionTimeout parameter to 3, my system has been up and running for five days straight.

**Comment by nixs64** [comment]
s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing...
----------------------------------------------------------- Hass.io
Add-on: Plejd Adds support for the Swedish home automation devices
from Plejd.-----------------------------------------------------------
Add-on version: 0.3.5 You are running the latest version of this
add-on.
parse error: Expected string key before ':' at line 1, column 4
[13:31:51] ERROR: Unknown HTTP error occured System:   (armv7 /
raspberrypi3) Home Assistant version: 0.105.3 Supervisor version:
200----------------------------------------------------------- Please,
share the above information when looking for help or support in, e.g.,
GitHub, forums or the Discord
chat.-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing...
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:31:54] INFO: Starting the Plejd service...
[13:31:54] INFO: Verified permissions on startup script
[13:31:54] INFO: Executing startup script
[13:31:57] INFO: Wrote plejd.json
[13:31:57] INFO: Running add-on
starting Plejd add-on v. 0.3.5
plejd-api: login()
plejd-api: logging into Niklas Sjostedt
plejd-api: got session token response
plejd-api: getCryptoKey()
plejd-api: got sites response
wireEvents()
init()
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light named Hanne Alkov with PID 135.
plejd-mqtt: discovered light named Badrum Nere Tak with PID 59.
plejd-mqtt: discovered light named Hanne Tak with PID 143.
plejd-mqtt: discovered light named Korridor Tak with PID 45.
plejd-mqtt: discovered light named Jesper Fönstersmyg  with PID 95.
plejd-mqtt: discovered light named Sovrum Fönstersmyg with PID 81.
plejd-mqtt: discovered light named Köksbord Taklampa  with PID 26.
plejd-mqtt: discovered light named Kontor Tak  with PID 21.
plejd-mqtt: discovered light named Badrum Uppe Tak with PID 126.
plejd-mqtt: discovered light named Jesper Alkov with PID 100.
plejd-mqtt: discovered light named Vardagsrum Uppe Fönstersmyg with PID 91.
plejd-mqtt: discovered light named Utebelysning Veranda with PID 153.
plejd-mqtt: discovered light named Badrum Nere Fönstersmyg  with PID 77.
plejd-mqtt: discovered light named Jesper Tak with PID 113.
plejd-mqtt: discovered light named Kök Tak with PID 40.
plejd-mqtt: discovered light named Badrum Uppe Fönstersmyg  with PID 130.
plejd-mqtt: discovered light named Utebelysning Altandörr Kök with PID 49.
plejd-mqtt: discovered light named Vardagsrum Nere Tak with PID 64.
plejd-mqtt: discovered light named Hall with PID 69.
plejd-mqtt: discovered light named Utebelysning Garage with PID 147.
plejd-mqtt: discovered light named Sovrum with PID 54.
plejd-mqtt: discovered light named Hanne Fönstersmyg with PID 139.
plejd-mqtt: discovered light named Kontor Fönstersmyg with PID 85.
plejd-mqtt: discovered light named Fönstersmyg, Vardagsrum, Hall,
Matplats with PID 16.
plejd-mqtt: discovered light named Utebelysning Altandörr Övervåning
with PID 117.
plejd-mqtt: discovered light named Utebelysning Källardörr with PID 121.
plejd-mqtt: discovered light named Matplats Tak with PID 30.
plejd-mqtt: discovered light named Kök Vitrinskåp, Överskåp with PID 73.
plejd-mqtt: discovered light named Vardagsrum Uppe Tak with PID 104.
plejd-mqtt: discovered light named Trappa with PID 109.
plejd-mqtt: discovered light named Köksbänk Tak with PID 36.
onDeviceConnected()
plejd-ble: warning: wasn't able to connect to Plejd, will retry.
plejd-ble: were unable to connect, will retry connection in 10 seconds.
(node:290) UnhandledPromiseRejectionWarning: DBusError: Operation
already in progress
    at _methodReturnHandlers.(anonymous function)
(/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on
(/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:555:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:290) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 1)
(node:290) [DEP0018] DeprecationWarning: Unhandled promise rejections
are deprecated. In the future, promise rejections that are not handled
will terminate the Node.js process with a non-zero exit code.
init()
plejd-ble: error: failed to start discovery. Make sure no other add-on
is currently scanning.


Den lör 8 feb. 2020 18:29martach <notifications@github.com> skrev:

**Comment by icanos** [comment]
Please try to tweak your connectionTimeout parameter in the settings, somewhere between 2-4 should do it.

**Comment by icanos** [comment]
Closing due to inactivity.
