### ISSUE TITLE
ble not found

### ISSUE THREAD

**Issue by emmedbemme** [icanos/hassio-plejd#211]
My plejd system was working yesterdat then i fu***d up my dnsmasq installation uninstalled the plugin via ssh then logged and got this error reapeting. But the wierd thing is it seams to connect via bluetooth and find all devices in the begining and then it disconects.

Please help

> 2021-07-14 20:57:42 INF [plejd-main] Log level set to info
Starting Plejd addon and reading configuration...
2021-07-14 20:57:42 INF [plejd-main] Log level set to info
2021-07-14 20:57:42 INF [plejd-main] Plejd add-on, version 0.8.0-beta
2021-07-14 20:57:42 INF [device-comm] Starting Plejd communication handler.
2021-07-14 20:57:42 INF [plejd-ble] Starting Plejd BLE Handler, resetting all device states.
2021-07-14 20:57:42 INF [plejd-main] Main Plejd addon init()...
2021-07-14 20:57:42 INF [plejd-api] init()
2021-07-14 20:57:42 INF [plejd-api] Getting cached api response from disk
2021-07-14 20:57:43 INF [plejd-api] login()
2021-07-14 20:57:43 INF [plejd-api] logging into Murare
2021-07-14 20:57:43 INF [plejd-api] got session token response
2021-07-14 20:57:43 INF [plejd-api] Get all Plejd sites for account...
2021-07-14 20:57:43 INF [plejd-api] Got site list response with 1: Murare
2021-07-14 20:57:43 INF [plejd-api] Site found matching configuration name Murare
2021-07-14 20:57:43 INF [plejd-api] Get site details for 164b20d3-0568-4c0f-b56a-e9e72b89f42a...
2021-07-14 20:57:44 INF [plejd-api] got site details response
2021-07-14 20:57:44 INF [plejd-api] Site details for site id 164b20d3-0568-4c0f-b56a-e9e72b89f42a found
2021-07-14 20:57:44 INF [plejd-api] Saving cached copy
2021-07-14 20:57:44 INF [plejd-api] Getting devices from site details response...
2021-07-14 20:57:44 INF [plejd-api] Plejd gateway 'Vid Routern' found on site
2021-07-14 20:57:44 INF [plejd-mqtt] Initializing MQTT connection for Plejd addon
2021-07-14 20:57:45 INF [plejd-ble] init()
2021-07-14 20:57:45 INF [plejd-mqtt] Connected to MQTT.
2021-07-14 20:57:45 ERR [plejd-ble] Unable to find a bluetooth adapter that is compatible.
2021-07-14 20:57:45 ERR [device-comm] Failed init() of BLE. Starting reconnect loop.
2021-07-14 20:57:45 INF [plejd-ble] Starting reconnect loop...
2021-07-14 20:57:45 INF [device-comm] Bluetooth reconnecting...
2021-07-14 20:57:45 INF [plejd-mqtt] Sending discovery for 25 Plejd output devices
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered DIM-01 (light) named Trapp till öv (11 : E107A2C692FC_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered DIM-01 (light) named Tak TV (21 : C5D4204F55D5_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered CTR-01 (light) named Plank (26 : F72164B9E240_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered DIM-01 (light) named Sovrum spott m gata (16 : CDD1192CC66D_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered DIM-01 (light) named Smyg (35 : FE6A1D6BD1B8_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered CTR-01 (switch) named Fläkt altan (31 : DF0E9732165F_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered DIM-01 (light) named Pool (39 : F98DE5BD804F_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered DIM-01 (light) named Badrum 1 (48 : E21EE6DCEDE3_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered DIM-01 (light) named Badrum 2 (44 : C942A03AC869_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered DIM-01 (light) named Lilla sov taklampa (54 : D259A053ACD1_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered LED-10 (light) named Vitrinskåp (58 : F6B070FD90D8_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered LED-10 (light) named Bastu (62 : F2FA8B47A433_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered DIM-01 (light) named Gert sänglampa (63 : E9990EE988E3_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered DIM-01 (light) named Sandra sänglampa (64 : DFB810E1F74B_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered DIM-01 (light) named Fönster läsrum (68 : E4BB4AFD23D1_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered LED-10 (light) named Altansmyg (69 : DF32F0AB68F3_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered DIM-01 (light) named Taklampa (57 : D2D775DC3A76_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered DIM-01 (light) named Murbelysning (70 : DB48260E56A9_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered DIM-01 (light) named Skrivbord (71 : EFA817368A6F_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered DIM-01 (light) named spegel hall (72 : CD6396D08ACE_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered CTR-01 (light) named Björken (73 : F2B695EF63CF_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered DIM-01 (light) named Belysning framsida hus (75 : E19921E4A1A7_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered DIM-01 (light) named Hall övre (76 : FD107698A684_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered DIM-01 (light) named Led tak trappuppgång  (77 : C7502C6C8177_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered DIM-01 (light) named Entrén  (78 : D54D139D05FD_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Sending discovery for 12 Plejd input devices
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named Gert sängbord (59 : D9262CC19142_I_2).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named Gert sängbord (59 : D9262CC19142_I_1).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named Gert sängbord (59 : D9262CC19142_I_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named Gert sängbord (59 : D9262CC19142_I_3).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named Sandra sängbord (65 : C20C8D13DD05_I_1).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named Sandra sängbord (65 : C20C8D13DD05_I_3).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named Sandra sängbord (65 : C20C8D13DD05_I_2).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named Sandra sängbord (65 : C20C8D13DD05_I_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named Hall uppe (74 : F07B8F9ED9A0_I_1).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named Hall uppe (74 : F07B8F9ED9A0_I_2).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named Hall uppe (74 : F07B8F9ED9A0_I_3).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named Hall uppe (74 : F07B8F9ED9A0_I_0).
2021-07-14 20:57:45 INF [plejd-mqtt] Sending discovery for 7 Plejd scene devices
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered Scene (scene) named Toa 90% (13 : 2f682f96-4338-42d5-b09d-504e0c3f8aec).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered Scene (scene) named Städ (12 : 2e365281-520f-46b8-9045-c66793270e1f).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered Scene (scene) named Toa kväll (14 : 40f21e24-5cf0-47e5-978e-98de3147cead).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered Scene (scene) named Emrik mys belysning (19 : 0a9d63bc-31a4-4366-95ce-56f683463d61).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered Scene (scene) named Släck Helt Emrik (21 : abd99e48-05dc-4ed9-b871-5a9ab81cba15).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered Scene (scene) named Emrik tänd (18 : ba5ff0bd-cde5-4a37-9572-0df23d137cd0).
2021-07-14 20:57:45 INF [plejd-mqtt] Discovered Scene (scene) named Entré + trapp 10% (22 : 313b0619-63a4-4e1d-859f-ebb4f65783b5).
2021-07-14 20:57:45 INF [device-comm] Plejd got turn on command for Trapp till öv (E107A2C692FC_0), brightness undefined
2021-07-14 20:57:45 INF [device-comm] Plejd got turn off command for Tak TV (C5D4204F55D5_0)
2021-07-14 20:57:45 INF [device-comm] Plejd got turn off command for Smyg (FE6A1D6BD1B8_0)
2021-07-14 20:57:45 INF [device-comm] Plejd got turn on command for Lilla sov taklampa (D259A053ACD1_0), brightness 163
2021-07-14 20:57:45 INF [device-comm] Plejd got turn on command for Sandra sänglampa (DFB810E1F74B_0), brightness 102
2021-07-14 20:57:45 INF [device-comm] Plejd got turn on command for Taklampa (D2D775DC3A76_0), brightness undefined
2021-07-14 20:57:45 INF [device-comm] Plejd got turn on command for Skrivbord (EFA817368A6F_0), brightness undefined
2021-07-14 20:57:50 INF [plejd-ble] Reconnecting BLE...
2021-07-14 20:57:50 INF [plejd-ble] init()
2021-07-14 20:57:50 ERR [plejd-ble] Unable to find a bluetooth adapter that is compatible.
2021-07-14 20:57:50 WRN [plejd-ble] Failed reconnecting. Unable to find a bluetooth adapter that is compatible.
Error: Unable to find a bluetooth adapter that is compatible.
    at PlejBLEHandler._getInterface (/plejd/PlejdBLEHandler.js:356:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async PlejBLEHandler.init (/plejd/PlejdBLEHandler.js:152:5)
    at async PlejBLEHandler._startReconnectPeriodicallyLoopInternal (/plejd/PlejdBLEHandler.js:542:9)
    at async PlejBLEHandler.startReconnectPeriodicallyLoop (/plejd/PlejdBLEHandler.js:488:5)
    at async PlejdDeviceCommunication.init (/plejd/PlejdDeviceCommunication.js:75:7)
    at async PlejdAddon.init (/plejd/PlejdAddon.js:157:5)
    at async main (/plejd/main.js:18:5)

**Comment by SweVictor** [comment]
Don't know what the error is, but the BLE mesh is NOT up and running according to the logs. The `plejd-api` is HTTP response from the plejd API. The `plejd-mqtt` sends api-found devices to home assistant. Only the `plejd-ble` logs and `device-comm` are relevant for the BLE connectivity. Do have a look in the troubleshooting part of the readme for some initial pointers
