### ISSUE TITLE
Unable to connect I think?

### ISSUE THREAD

**Issue by JacobWiqvist** [icanos/hassio-plejd#217]
Hi All!

I get this error message when trying to connect to Plejd, any one have any idea?

 Add-on: Plejd
 Adds support for the Swedish home automation devices from Plejd.
-----------------------------------------------------------
 Add-on version: 0.8.0-beta
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[16:55:46] ERROR: Unknown HTTP error occured
 System:   (armv7 / raspberrypi4)
 Home Assistant Core: 2021.9.7
 Home Assistant Supervisor: 2021.09.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:55:47] INFO: Starting the Plejd service...
[16:55:47] INFO: Verified permissions on startup script
[16:55:47] INFO: Executing startup script
[16:55:47] INFO: Running add-on
Config: {
  site: 'Jacob',
  username: '---scrubbed---',
  password: '---scrubbed---',
  mqttBroker: 'core-mosquitto',
  mqttUsername: 'Jacob',
  mqttPassword: '---scrubbed---',
  includeRoomsAsLights: true,
  preferCachedApiResponse: true,
  updatePlejdClock: false,
  logLevel: 'info',
  connectionTimeout: 2,
  writeQueueWaitTime: 800
}
2021-09-26 16:55:48 INF [plejd-main] Log level set to info
Starting Plejd addon and reading configuration...
2021-09-26 16:55:48 INF [plejd-main] Log level set to info
2021-09-26 16:55:48 INF [plejd-main] Plejd add-on, version 0.8.0-beta
2021-09-26 16:55:48 INF [device-comm] Starting Plejd communication handler.
2021-09-26 16:55:48 INF [plejd-ble] Starting Plejd BLE Handler, resetting all device states.
2021-09-26 16:55:48 INF [plejd-main] Main Plejd addon init()...
2021-09-26 16:55:48 INF [plejd-api] init()
2021-09-26 16:55:48 INF [plejd-api] Getting cached api response from disk
2021-09-26 16:55:49 INF [plejd-api] Cache preferred. Skipping api requests and setting api data to response from 2021-06-14T21:05:28.859Z
2021-09-26 16:55:49 INF [plejd-api] Getting devices from site details response...
2021-09-26 16:55:49 INF [plejd-api] Plejd gateway 'Mediacentral' found on site
2021-09-26 16:55:49 INF [plejd-mqtt] Initializing MQTT connection for Plejd addon
Catastrophic error. Resetting entire addon in 1 minute Error: Missing protocol
    at Object.connect (/plejd/node_modules/mqtt/lib/connect/index.js:71:13)
    at MqttClient.init (/plejd/MqttClient.js:151:24)
    at PlejdAddon.init (/plejd/PlejdAddon.js:124:21)
    at async main (/plejd/main.js:18:5)
Starting Plejd addon and reading configuration...
2021-09-26 16:56:49 INF [plejd-main] Log level set to info
2021-09-26 16:56:49 INF [plejd-main] Plejd add-on, version 0.8.0-beta
2021-09-26 16:56:49 INF [device-comm] Starting Plejd communication handler.
2021-09-26 16:56:49 INF [plejd-ble] Starting Plejd BLE Handler, resetting all device states.
2021-09-26 16:56:49 INF [plejd-main] Main Plejd addon init()...
2021-09-26 16:56:49 INF [plejd-api] init()
2021-09-26 16:56:49 INF [plejd-api] Getting cached api response from disk
2021-09-26 16:56:49 INF [plejd-api] Cache preferred. Skipping api requests and setting api data to response from 2021-06-14T21:05:28.859Z
2021-09-26 16:56:49 INF [plejd-api] Getting devices from site details response...
2021-09-26 16:56:49 INF [plejd-api] Plejd gateway 'Mediacentral' found on site
2021-09-26 16:56:49 INF [plejd-mqtt] Initializing MQTT connection for Plejd addon
Catastrophic error. Resetting entire addon in 1 minute Error: Missing protocol
    at Object.connect (/plejd/node_modules/mqtt/lib/connect/index.js:71:13)
    at MqttClient.init (/plejd/MqttClient.js:151:24)
    at PlejdAddon.init (/plejd/PlejdAddon.js:124:21)
    at async main (/plejd/main.js:18:5)

**Comment by JacobWiqvist** [comment]
this is what Mosqito Broker say:

[16:25:04] INFO: Successfully send service information to the Supervisor.
1632666302: New client connected from 172.30.32.1 as 5QM8j83vOnwLzkNHygF8BB (p2, c1, k60, u'homeassistant').
1632666371: New connection from 172.30.32.2 on port 1883.
1632666371: Socket error on client <unknown>, disconnecting.
1632666491: New connection from 172.30.32.2 on port 1883.
1632666491: Socket error on client <unknown>, disconnecting.
1632666611: New connection from 172.30.32.2 on port 1883.
1632666611: Socket error on client <unknown>, disconnecting.
1632666616: Client hassio-plejd_28631ae6 disconnected.
1632666731: New connection from 172.30.32.2 on port 1883.
1632666731: Socket error on client <unknown>, disconnecting.
1632666851: New connection from 172.30.32.2 on port 1883.
1632666851: Socket error on client <unknown>, disconnecting.
1632666971: New connection from 172.30.32.2 on port 1883.
1632666971: Socket error on client <unknown>, disconnecting.
1632666991: New connection from 192.168.1.134 on port 1883.
{"result": "ok", "data": {}}1632666992: New client connected from 192.168.1.134 as hassio-plejd_929e9e72 (p2, c1, k60, u'Jacob').
1632667091: New connection from 172.30.32.2 on port 1883.
1632667091: Socket error on client <unknown>, disconnecting.
1632667211: New connection from 172.30.32.2 on port 1883.
1632667211: Socket error on client <unknown>, disconnecting.
1632667331: New connection from 172.30.32.2 on port 1883.
1632667331: Socket error on client <unknown>, disconnecting.
1632667451: New connection from 172.30.32.2 on port 1883.
1632667451: Socket error on client <unknown>, disconnecting.
1632667571: New connection from 172.30.32.2 on port 1883.
1632667571: Socket error on client <unknown>, disconnecting.
1632667677: Client hassio-plejd_929e9e72 disconnected.
1632667691: New connection from 172.30.32.2 on port 1883.
1632667691: Socket error on client <unknown>, disconnecting.
1632667811: New connection from 172.30.32.2 on port 1883.
1632667811: Socket error on client <unknown>, disconnecting.
1632667931: New connection from 172.30.32.2 on port 1883.
1632667931: Socket error on client <unknown>, disconnecting.
1632668051: New connection from 172.30.32.2 on port 1883.

**Comment by JacobWiqvist** [comment]
The log also say this:

-----------------------------------------------------------
 Add-on: Plejd
 Adds support for the Swedish home automation devices from Plejd.
-----------------------------------------------------------
 Add-on version: 0.8.0-beta
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[17:13:28] ERROR: Unknown HTTP error occured
 System:   (armv7 / raspberrypi4)
 Home Assistant Core: 2021.9.7
 Home Assistant Supervisor: 2021.09.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------

**Comment by JacobWiqvist** [comment]
I re installed the add-on and MQTT broker.

And about the same error:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Plejd
 Adds support for the Swedish home automation devices from Plejd.
-----------------------------------------------------------
 Add-on version: 0.8.0-beta
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[18:38:08] ERROR: Unknown HTTP error occured
 System:   (armv7 / raspberrypi4)
 Home Assistant Core: 2021.9.7
 Home Assistant Supervisor: 2021.09.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:38:09] INFO: Starting the Plejd service...
[18:38:09] INFO: Verified permissions on startup script
[18:38:09] INFO: Executing startup script
[18:38:09] INFO: Running add-on
Config: {
  site: 'Jacob',
  username: '---scrubbed---',
  password: '---scrubbed---',
  mqttBroker: 'core-mosquitto',
  mqttUsername: 'Jacob',
  mqttPassword: '---scrubbed---',
  includeRoomsAsLights: true,
  preferCachedApiResponse: false,
  updatePlejdClock: false,
  logLevel: 'info',
  connectionTimeout: 2,
  writeQueueWaitTime: 400
}
2021-09-26 18:38:10 INF [plejd-main] Log level set to info
Starting Plejd addon and reading configuration...
2021-09-26 18:38:10 INF [plejd-main] Log level set to info
2021-09-26 18:38:10 INF [plejd-main] Plejd add-on, version 0.8.0-beta
2021-09-26 18:38:10 INF [device-comm] Starting Plejd communication handler.
2021-09-26 18:38:10 INF [plejd-ble] Starting Plejd BLE Handler, resetting all device states.
2021-09-26 18:38:10 INF [plejd-main] Main Plejd addon init()...
2021-09-26 18:38:10 INF [plejd-api] init()
2021-09-26 18:38:10 INF [plejd-api] Getting cached api response from disk
2021-09-26 18:38:10 WRN [plejd-api] No cached api response could be read. This is normal on the first run ENOENT: no such file or directory, open '/data/cachedApiResponse.json'
Error: ENOENT: no such file or directory, open '/data/cachedApiResponse.json'
2021-09-26 18:38:10 INF [plejd-api] login()
2021-09-26 18:38:10 INF [plejd-api] logging into Jacob


If anyone have any idea it would be good!
2021-09-26 18:38:11 INF [plejd-api] got session token response
2021-09-26 18:38:11 INF [plejd-api] Get all Plejd sites for account...
2021-09-26 18:38:11 INF [plejd-api] Got site list response with 2: , Jacob
2021-09-26 18:38:11 INF [plejd-api] Site found matching configuration name Jacob
2021-09-26 18:38:11 INF [plejd-api] Get site details for 65514145-d814-4e5d-bc83-62a214f35c46...
2021-09-26 18:38:12 INF [plejd-api] got site details response
2021-09-26 18:38:12 INF [plejd-api] Site details for site id 65514145-d814-4e5d-bc83-62a214f35c46 found
2021-09-26 18:38:12 INF [plejd-api] Saving cached copy
2021-09-26 18:38:12 INF [plejd-api] Getting devices from site details response...
2021-09-26 18:38:12 INF [plejd-api] Plejd gateway 'Mediacentral' found on site
2021-09-26 18:38:13 INF [plejd-mqtt] Initializing MQTT connection for Plejd addon
Catastrophic error. Resetting entire addon in 1 minute Error: Missing protocol
    at Object.connect (/plejd/node_modules/mqtt/lib/connect/index.js:71:13)
    at MqttClient.init (/plejd/MqttClient.js:151:24)
    at PlejdAddon.init (/plejd/PlejdAddon.js:124:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/plejd/main.js:18:5)

**Comment by SweVictor** [comment]
Mqtt missing protocol, maybe the config is missing the mqtt:// part? The error is most certainly from the mqtt library, not this add-on.

Apart from that, very little plejd-ble logs so BLE communication to the device network is probably not up yet.

**Comment by JacobWiqvist** [comment]
This is the Mosquito log:

[06:35:41] INFO: Setting up user jwiqvist
[06:35:42] INFO: SSL is not enabled
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[06:35:43] INFO: Starting NGINX for authentication handling...
[06:35:43] INFO: Starting mosquitto MQTT broker...
1632717343: mosquitto version 1.6.12 starting
1632717343: |-- *** auth-plug: startup
[06:35:44] INFO: Successfully send discovery information to Home Assistant.
[06:35:44] INFO: Successfully send service information to the Supervisor.
1632717343: Config loaded from /etc/mosquitto/mosquitto.conf.
1632717343: Loading plugin: /usr/share/mosquitto/auth-plug.so
1632717343:  ├── Username/password checking enabled.
1632717343:  ├── TLS-PSK checking enabled.
1632717343:  └── Extended authentication not enabled.
1632717343: Opening ipv4 listen socket on port 1883.
1632717343: Opening ipv6 listen socket on port 1883.
1632717343: Opening websockets listen socket on port 1884.
1632717343: Warning: Mosquitto should not be run as root/administrator.
1632717343: mosquitto version 1.6.12 running
1632717343: New connection from 192.168.1.134 on port 1883.
1632717343: New connection from 127.0.0.1 on port 1883.
1632717343: New client connected from 192.168.1.134 as hassio-plejd_ddac623b (p2, c1, k60, u'jwiqvist').
1632717343: Socket error on client <unknown>, disconnecting.
1632717353: New connection from 172.30.32.1 on port 1883.
401: Unauthorized1632717353: Socket error on client <unknown>, disconnecting.

No idea what is wrong?

**Comment by JacobWiqvist** [comment]
This is the latest Plejd log:     at PlejBLEHandler._startGetPlejdDevice (/plejd/PlejdBLEHandler.js:436:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-09-27 06:38:49 INF [device-comm] Bluetooth reconnecting...
2021-09-27 06:38:53 ERR [plejd-ble] Discovery timeout elapsed, no devices found. Starting reconnect loop...
2021-09-27 06:38:53 INF [plejd-ble] Starting reconnect loop...
2021-09-27 06:38:54 INF [plejd-ble] Reconnecting BLE...
2021-09-27 06:38:54 INF [plejd-ble] init()
(node:304) UnhandledPromiseRejectionWarning: DBusError: Resource Not Ready
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(node:304) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
2021-09-27 06:38:59 ERR [plejd-ble] Failed to start discovery. Resource Not Ready
DBusError: Resource Not Ready
    at _methodReturnHandlers.<c

**Comment by SweVictor** [comment]
The mqtt log I don't know much about. My mqtt config looks like this if that helps `mqtt://localhost`

The plejd log indicates the BLE mesh is not up and running. There are many issues talking about similar problems, some for RPI4. Have a look at those and the troubleshooting in the readme. 

Things to test include increasing connection timeout, moving BLE adapter closer to physical Plejd device, restarting, testing.

**Comment by Tozzi89** [comment]
It looks like you have wrong info about mqtt login info. Could you please provide what users you have, what mqtt uses and what plejd is suppose to use?

**Comment by JacobWiqvist** [comment]
Where can I see that?

Best regards Jacob

lör 6 nov. 2021 kl. 13:41 skrev Tobias ***@***.***>:

**Comment by JacobWiqvist** [comment]
I manage to get MQTT to work. I hade wrong name.

But now I get this.

Restarted RapberyPie and let it cool down but the same strange error?


This is the log:

2021-11-16 20:35:22 INF [plejd-main] Log level set to info
Starting Plejd addon and reading configuration...
2021-11-16 20:35:22 INF [plejd-main] Log level set to info
2021-11-16 20:35:22 INF [plejd-main] Plejd add-on, version 0.8.0-beta
2021-11-16 20:35:22 INF [device-comm] Starting Plejd communication handler.
2021-11-16 20:35:22 INF [plejd-ble] Starting Plejd BLE Handler,
resetting all device states.
2021-11-16 20:35:22 INF [plejd-main] Main Plejd addon init()...
2021-11-16 20:35:22 INF [plejd-api] init()
2021-11-16 20:35:22 INF [plejd-api] Getting cached api response from disk
2021-11-16 20:35:22 INF [plejd-api] login()
2021-11-16 20:35:22 INF [plejd-api] logging into Jacob
2021-11-16 20:35:23 INF [plejd-api] got session token response
2021-11-16 20:35:23 INF [plejd-api] Get all Plejd sites for account...
2021-11-16 20:35:23 INF [plejd-api] Got site list response with 2: , Jacob
2021-11-16 20:35:23 INF [plejd-api] Site found matching configuration name Jacob
2021-11-16 20:35:23 INF [plejd-api] Get site details for
65514145-d814-4e5d-bc83-62a214f35c46...
2021-11-16 20:35:24 INF [plejd-api] got site details response
2021-11-16 20:35:24 INF [plejd-api] Site details for site id
65514145-d814-4e5d-bc83-62a214f35c46 found
2021-11-16 20:35:24 INF [plejd-api] Saving cached copy
2021-11-16 20:35:24 INF [plejd-api] Getting devices from site details
response...
2021-11-16 20:35:24 INF [plejd-api] Plejd gateway 'Mediacentral' found on site
2021-11-16 20:35:25 INF [plejd-mqtt] Initializing MQTT connection for
Plejd addon
2021-11-16 20:35:25 INF [plejd-ble] init()
2021-11-16 20:35:25 INF [plejd-mqtt] Connected to MQTT.
2021-11-16 20:35:25 INF [plejd-mqtt] Sending discovery for 32 Plejd
output devices
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered DIM-01 (light) named
Hanna Tak (11 : E19E9D014FD5_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered DIM-01 (light) named
Vardagsrum Tak (16 : D3B68BF027F1_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered DIM-01 (light) named
Badrum Nedre (21 : D2D21FBE1B1C_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered DIM-01 (light) named
Kontor tak (26 : F5F5CE6AD301_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered DIM-01 (light) named
Kontor Säng (30 : EBE53F311518_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered DIM-01 (light) named
Hall mitten (52 : DD88038432C2_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered DIM-01 (light) named
Trappa Huvudentré (43 : DCB41586D97D_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered DIM-01 (light) named
Hall Övervåning (39 : C2D63538C317_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered DIM-01 (light) named
Trappa  (35 : C571BFCC5D21_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered DIM-01 (light) named
Hall Groventre’ (48 : EF5C6A678E67_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered DIM-01 (light) named
Victor Säng (61 : F2B2B6FD4110_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered DIM-01 (light) named
Victor Tak (57 : D6E7D250082B_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered DIM-01 (light) named
Övervåning Soffa (69 : D82A2037A766_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered DIM-01 (light) named
Hanna Säng (73 : DC6ADEF13B19_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered DIM-01 (light) named
Ytterbelysning (78 : EF3D3AEF524C_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered CTR-01 (light) named
Fläkt simulator (80 : E85238C726DF_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered DIM-01 (light) named
Storarum Tak (65 : D2FAAB9E2EE6_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered DIM-01 (light) named
Storarum Spot (66 : E9DEABE6AE3B_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered DIM-01 (light) named
Storarum Säng1 (67 : CC7DB9E2E57F_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered DIM-01 (light) named
Storarum Säng2 (68 : F5821E28F925_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered DIM-01 (light) named
AllrumTak Storarum (83 : E5DE8D585CEA_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered -unknown- (light)
named Spottar (87 : DE2D82ECDCB2_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered Room (light) named
Hanna rum (10 : b524da0e-4081-43aa-a668-4ac76050468e).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered Room (light) named
Vardagsrum / Allrum  (15 : 18d26772-9ab3-4a79-97cc-a4150137dca3).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered Room (light) named
Toalett (20 : 09dd249c-c120-441b-8254-781e28383a7d).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered Room (light) named
Kontor (25 : 6b940a50-eda2-4aa8-8435-f3d4939f89e4).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered Room (light) named
Entré / Hall (47 : 66217bf7-0e52-4db6-b710-aab7bbbc218f).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered Room (light) named
Övervåning  (34 : c8ae682c-e309-4610-8b2d-d831aa64af28).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered Room (light) named
Victor rum (56 : 297c0574-15bf-4802-803a-63a5c76d871b).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered Room (light) named
Utomhus  (77 : ddf014ad-b817-4e6d-9574-896df26d259e).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered Room (light) named
Stora Sovrum (81 : 94cbd81c-5abc-48ab-a8d4-08114b43d5c8).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered Room (light) named Kök
/ Matplats (86 : 151cc033-0ab9-4be4-9af7-666897c47a38).
2021-11-16 20:35:25 INF [plejd-mqtt] Sending discovery for 6 Plejd input devices
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered WPH-01
(device_automation) named Hall WC (79 : F9DA6143B097_I_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered WPH-01
(device_automation) named Hall WC (79 : F9DA6143B097_I_1).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered WPH-01
(device_automation) named Hall WC (79 : F9DA6143B097_I_2).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered WPH-01
(device_automation) named Hall WC (79 : F9DA6143B097_I_3).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered WRT-01
(device_automation) named Trappa (82 : C9C36465787F_I_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered WRT-01
(device_automation) named Kök vid entrén  (88 : EC701B6CF258_I_0).
2021-11-16 20:35:25 INF [plejd-mqtt] Sending discovery for 9 Plejd scene devices
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered Scene (scene) named
Övervåning Mys (19 : f7c1b9d2-84e0-4003-aa25-2ed1d88d539f).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered Scene (scene) named
Övervåning Soffa 100% (1 : 4a628c6d-92de-4fb9-a6ae-8de0d87c3a50).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered Scene (scene) named
Övervåning + Rum 0% (24 : 23175a09-8a7c-49e3-9320-2c3866bcd95c).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered Scene (scene) named
Övervåning Städ 100% (25 : 8c896488-0cec-4124-ad8a-f928882cff9d).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered Scene (scene) named
Övervåning Sova (26 : b3ce21e9-ed73-47ee-b452-c0717e10db6c).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered Scene (scene) named
63% fläkt (30 : d01ac9ba-0ca6-432a-959c-4eea48db335f).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered Scene (scene) named
Fläkt 92% (29 : 86b857b3-bd33-4e43-ab58-8730329c7c5d).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered Scene (scene) named
Hem flyg (31 : 7fcea746-3698-44ed-a0d2-1f1d6daf27f3).
2021-11-16 20:35:25 INF [plejd-mqtt] Discovered Scene (scene) named
Natt Victor Hanna (32 : ad926883-2d9c-4414-a084-04981cf97693).
(node:302) UnhandledPromiseRejectionWarning: DBusError: Resource Not Ready
    at _methodReturnHandlers.<computed>
(/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(node:302) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was
not handled with .catch(). To terminate the node process on unhandled
promise rejection, use the CLI flag `--unhandled-rejections=strict`
(see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode).
(rejection id: 1)
(node:302) [DEP0018] DeprecationWarning: Unhandled promise rejections
are deprecated. In the future, promise rejections that are not handled
will terminate the Node.js process with a non-zero exit code.
2021-11-16 20:35:30 ERR [plejd-ble] Failed to start discovery.
Resource Not Ready
DBusError: Resource Not Ready
    at _methodReturnHandlers.<computed>
(/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2021-11-16 20:35:30 ERR [device-comm] Failed init() of BLE. Starting
reconnect loop.
2021-11-16 20:35:30 INF [plejd-ble] Starting reconnect loop...
2021-11-16 20:35:30 INF [device-comm] Bluetooth reconnecting...


Den lör 6 nov. 2021 kl 13:41 skrev Tobias ***@***.***>:

**Comment by JacobWiqvist** [comment]
Is ther any one that have a solution. I cant connect to Plejd, for a long time now?

**Comment by SweVictor** [comment]
Sorry to hear that. The below lines basically says that the BLE communication is not up
```
2021-11-16 20:35:30 INF [plejd-ble] Starting reconnect loop...
2021-11-16 20:35:30 INF [device-comm] Bluetooth reconnecting...
```

The `UnhandledPromiseRejection` is a BLE library we're using not catching errors correctly, but the actual error is `DBusError: Resource not ready`. Something to do with the BLE hardware and/or the library communicating with that, but unfortunately I don't know more than that.

**Comment by JacobWiqvist** [comment]
What would you suggest doing?

tors 18 nov. 2021 kl. 16:00 skrev Victor ***@***.***>:

**Comment by SweVictor** [comment]
Well... I would look at old issues for Rpi4 or for BLE issues. Follow troubleshooting section in readme (move closer to Plejd puck, make sure BLE works from the console, gather verbose logs although I'm not sure they would help here). You could try manually installing a quite old version of you want. Some have succeeded after getting a new BLE adapter. You could go deep and dig through issues in the BLE libs we use. You could ask in some RPi forums for help.

**Comment by textta0** [comment]
is anyone active here
