### ISSUE TITLE
Dosn´t work after latest Hassio update

### ISSUE THREAD

**Issue by Mikro007** [icanos/hassio-plejd#223]
This addon have workt 100% with no problems at all the latest period. But now this week I update Hassio and after that it just stop working. I cant switch on any lights from hassio...

`    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2021-12-11 09:40:19 INF [plejd-ble] If you continue to get "operation already in progress" error, you can try power cycling the bluetooth adapter. Get root console access, run "bluetoothctl" => "power off" => "power on" => "exit" => restart addon.
2021-12-11 09:40:19 WRN [plejd-ble] Failed reconnecting. Failed to start discovery. Make sure no other add-on is currently scanning.
Error: Failed to start discovery. Make sure no other add-on is currently scanning.
    at PlejBLEHandler._startGetPlejdDevice (/plejd/PlejdBLEHandler.js:436:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-12-11 09:40:19 VRB [plejd-ble] Reconnect: Clean up, emit reconnect event, wait 5s and the re-init...
2021-12-11 09:40:19 VRB [plejd-ble] cleanup() - Clearing ping interval and clock update timer
2021-12-11 09:40:19 VRB [plejd-ble] Removing listeners to write events, bus events and objectManager...
2021-12-11 09:40:19 VRB [plejd-ble] Reconnect attempt 56 in a row. Will power cycle every 10th time.
2021-12-11 09:40:19 INF [device-comm] Bluetooth reconnecting...
2021-12-11 09:40:19 VRB [device-comm] Stopping writeQueue loop until connection is established. Write queue length: 23
2021-12-11 09:40:24 INF [plejd-ble] Reconnecting BLE...
2021-12-11 09:40:24 INF [plejd-ble] init()
2021-12-11 09:40:24 VRB [plejd-ble] Managed paths[
  "/org/bluez",
  "/org/bluez/hci0",
  "/org/bluez/hci0/dev_FC_F9_96_37_03_AF",
  "/org/bluez/hci0/dev_C0_AB_20_93_3D_47"
]
2021-12-11 09:40:24 DBG [plejd-ble] Found BLE interface 'org.bluez.Adapter1' at /org/bluez/hci0
2021-12-11 09:40:24 VRB [plejd-ble] Powering on BLE adapter and waiting 5 seconds
2021-12-11 09:40:29 VRB [plejd-ble] Iterating 4 BLE managedObjects looking for org.bluez.Device1
2021-12-11 09:40:29 VRB [plejd-ble] Found /org/bluez/hci0/dev_FC_F9_96_37_03_AF
2021-12-11 09:40:29 VRB [plejd-ble] Removing /org/bluez/hci0/dev_FC_F9_96_37_03_AF from adapter.
2021-12-11 09:40:29 VRB [plejd-ble] Found /org/bluez/hci0/dev_C0_AB_20_93_3D_47
2021-12-11 09:40:29 VRB [plejd-ble] Removing /org/bluez/hci0/dev_C0_AB_20_93_3D_47 from adapter.
2021-12-11 09:40:29 VRB [plejd-ble] All active BLE device connections cleaned up.
2021-12-11 09:40:29 VRB [plejd-ble] Got adapter undefined
2021-12-11 09:40:29 VRB [plejd-ble] Setting up interfacesAdded subscription and discovery filter
2021-12-11 09:40:29 VRB [plejd-ble] Starting BLE discovery... This can take up to 180 seconds.
2021-12-11 09:40:29 ERR [plejd-ble] Failed to start discovery. Operation already in progress
DBusError: Operation already in progress
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2021-12-11 09:40:29 INF [plejd-ble] If you continue to get "operation already in progress" error, you can try power cycling the bluetooth adapter. Get root console access, run "bluetoothctl" => "power off" => "power on" => "exit" => restart addon.
2021-12-11 09:40:29 WRN [plejd-ble] Failed reconnecting. Failed to start discovery. Make sure no other add-on is currently scanning.
Error: Failed to start discovery. Make sure no other add-on is currently scanning.
    at PlejBLEHandler._startGetPlejdDevice (/plejd/PlejdBLEHandler.js:436:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-12-11 09:40:29 VRB [plejd-ble] Reconnect: Clean up, emit reconnect event, wait 5s and the re-init...
2021-12-11 09:40:29 VRB [plejd-ble] cleanup() - Clearing ping interval and clock update timer
2021-12-11 09:40:29 VRB [plejd-ble] Removing listeners to write events, bus events and objectManager...
2021-12-11 09:40:29 VRB [plejd-ble] Reconnect attempt 57 in a row. Will power cycle every 10th time.
2021-12-11 09:40:29 INF [device-comm] Bluetooth reconnecting...
2021-12-11 09:40:29 VRB [device-comm] Stopping writeQueue loop until connection is established. Write queue length: 23
2021-12-11 09:40:34 INF [plejd-ble] Reconnecting BLE...
2021-12-11 09:40:34 INF [plejd-ble] init()
2021-12-11 09:40:34 VRB [plejd-ble] Managed paths[
  "/org/bluez",
  "/org/bluez/hci0",
  "/org/bluez/hci0/dev_FC_F9_96_37_03_AF",
  "/org/bluez/hci0/dev_C0_AB_20_93_3D_47"
]
2021-12-11 09:40:34 DBG [plejd-ble] Found BLE interface 'org.bluez.Adapter1' at /org/bluez/hci0
2021-12-11 09:40:34 VRB [plejd-ble] Powering on BLE adapter and waiting 5 seconds
2021-12-11 09:40:39 VRB [plejd-ble] Iterating 4 BLE managedObjects looking for org.bluez.Device1
2021-12-11 09:40:39 VRB [plejd-ble] Found /org/bluez/hci0/dev_FC_F9_96_37_03_AF
2021-12-11 09:40:39 VRB [plejd-ble] Removing /org/bluez/hci0/dev_FC_F9_96_37_03_AF from adapter.
2021-12-11 09:40:39 VRB [plejd-ble] Found /org/bluez/hci0/dev_C0_AB_20_93_3D_47
2021-12-11 09:40:39 VRB [plejd-ble] Removing /org/bluez/hci0/dev_C0_AB_20_93_3D_47 from adapter.
2021-12-11 09:40:39 VRB [plejd-ble] All active BLE device connections cleaned up.
2021-12-11 09:40:39 VRB [plejd-ble] Got adapter undefined
2021-12-11 09:40:39 VRB [plejd-ble] Setting up interfacesAdded subscription and discovery filter
2021-12-11 09:40:39 VRB [plejd-ble] Starting BLE discovery... This can take up to 180 seconds.
2021-12-11 09:40:39 ERR [plejd-ble] Failed to start discovery. Operation already in progress
DBusError: Operation already in progress
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2021-12-11 09:40:39 INF [plejd-ble] If you continue to get "operation already in progress" error, you can try power cycling the bluetooth adapter. Get root console access, run "bluetoothctl" => "power off" => "power on" => "exit" => restart addon.
2021-12-11 09:40:39 WRN [plejd-ble] Failed reconnecting. Failed to start discovery. Make sure no other add-on is currently scanning.
Error: Failed to start discovery. Make sure no other add-on is currently scanning.
    at PlejBLEHandler._startGetPlejdDevice (/plejd/PlejdBLEHandler.js:436:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-12-11 09:40:39 VRB [plejd-ble] Reconnect: Clean up, emit reconnect event, wait 5s and the re-init...
2021-12-11 09:40:39 VRB [plejd-ble] cleanup() - Clearing ping interval and clock update timer
2021-12-11 09:40:39 VRB [plejd-ble] Removing listeners to write events, bus events and objectManager...
2021-12-11 09:40:39 VRB [plejd-ble] Reconnect attempt 58 in a row. Will power cycle every 10th time.
2021-12-11 09:40:39 INF [device-comm] Bluetooth reconnecting...
2021-12-11 09:40:39 VRB [device-comm] Stopping writeQueue loop until connection is established. Write queue length: 23`

**Comment by sdool20** [comment]
Hello, I had the same issue. Plejd gateway was located to the HA computer (VM on synology NAS), moved the Plejd gateway away  and replaced it with a SPR-01 to be close to the USB BLE on the NAS and now it works!

**Comment by SweVictor** [comment]
@Mikro007 Are you still having issues? There is a new release out; that said your issue is probably hardware-related.

**Comment by LinusT** [comment]
I have the same issue as @Mikro007. The plejd addon worked initially. I have not since moved the switches or the Raspberry Pi4.

**Comment by Mikro007** [comment]
@SweVictor Sorry for late response but I havn´t used this since this issue come. Yesterday I installed a new hassio on my RPi 4 with SSD drive and at the first time it workt well, but later it stopped working again.

**Comment by Mikro007** [comment]
@SweVictor Could this be USB3-port related issue that reduces the BLE covarage?

https://community.home-assistant.io/t/rpi4-and-reduced-bluetooth-coverage-while-using-usb3-ssd/173251/5

**Comment by SweVictor** [comment]
Not sure, sorry, not running RPI myself.

**Comment by SweVictor** [comment]
Closing due to inactivity
