### ISSUE TITLE
Unable to find a bluetooth adapter that is compatible

### ISSUE THREAD

**Issue by Bjorekn** [icanos/hassio-plejd#234]
I'm having a problem with getting Bluetooth to work. I'm running intel nuc with i5-8259u and running home assist in hyper v. Have tried with both internal Bluetooth and Asus BT400

2022-03-07 20:07:23 INF [device-comm] Bluetooth reconnecting...
2022-03-07 20:07:28 INF [plejd-ble] Reconnecting BLE...
2022-03-07 20:07:28 INF [plejd-ble] init()
2022-03-07 20:07:28 ERR [plejd-ble] Unable to find a bluetooth adapter that is compatible.
2022-03-07 20:07:28 WRN [plejd-ble] Failed reconnecting. Unable to find a bluetooth adapter that is compatible.
Error: Unable to find a bluetooth adapter that is compatible.
    at PlejBLEHandler._getInterface (/plejd/PlejdBLEHandler.js:356:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async PlejBLEHandler.init (/plejd/PlejdBLEHandler.js:152:5)
    at async PlejBLEHandler._startReconnectPeriodicallyLoopInternal (/plejd/PlejdBLEHandler.js:542:9)
    at async PlejBLEHandler.startReconnectPeriodicallyLoop (/plejd/PlejdBLEHandler.js:488:5)
    at async PlejdDeviceCommunication.init (/plejd/PlejdDeviceCommunication.js:75:7)
    at async PlejdAddon.init (/plejd/PlejdAddon.js:157:5)
    at async main (/plejd/main.js:18:5)

**Comment by SweVictor** [comment]
Well... I run Windows 10 Pro host / Oracle VirtualBox 6.1 / Home Assistant VBox image / Deltaco BT-118 with Cambridge Silicon Radio chipset / Windows + Zadig to change driver to WinUSB. Not sure if that helps, but I think I found there were issues with Hyper-V and USB adapters that made me abandon that.

**Comment by dodg3r** [comment]
Hi.
How do you passthrough the bluetooth adapter in hyper V?

**Comment by SweVictor** [comment]
I don't think USB devices to a Linux vm is supported at all in hyper v

**Comment by tomoqv** [comment]
I have the same problem since a while back, with HA running on an Intel NUC supervised installation with Debian. It worked initially, when I set it up, but now I get this error from the log:
```
2022-04-26 19:01:11 INF [device-comm] Bluetooth reconnecting...
2022-04-26 19:01:16 INF [plejd-ble] Reconnecting BLE...
2022-04-26 19:01:16 INF [plejd-ble] init()
2022-04-26 19:01:16 ERR [plejd-ble] Unable to find a bluetooth adapter that is compatible.
2022-04-26 19:01:16 WRN [plejd-ble] Failed reconnecting. Unable to find a bluetooth adapter that is compatible.
Error: Unable to find a bluetooth adapter that is compatible.
```

I have bluetooth running (with the NUC built-in BT controller) on the host as shown below:
```
~$ sudo systemctl status bluetooth
● bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-04-26 18:11:59 CEST; 51min ago
       Docs: man:bluetoothd(8)
   Main PID: 8551 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 19034)
     Memory: 680.0K
        CPU: 359ms
     CGroup: /system.slice/bluetooth.service
             └─8551 /usr/libexec/bluetooth/bluetoothd

apr 26 18:11:59 HomeAssistant systemd[1]: Starting Bluetooth service...
apr 26 18:11:59 HomeAssistant bluetoothd[8551]: Bluetooth daemon 5.55
apr 26 18:11:59 HomeAssistant systemd[1]: Started Bluetooth service.
apr 26 18:11:59 HomeAssistant bluetoothd[8551]: Starting SDP server
apr 26 18:11:59 HomeAssistant bluetoothd[8551]: Bluetooth management interface 1.18 initialized

```

**Comment by tomoqv** [comment]
This turned out to be an issue with my Intel NUC machine. After a power off, waiting a while and then powering on again it all works now. I was really getting some grey hairs over this…

**Comment by ajaandreas** [comment]
Hi,

I have the same issue running Home Assistant via Hassio on a RaspberryPi 3B. The plugin works from time to time, but usually stops working after a few hours. Sometimes a restart helps, sometimes not. I have exactly the same log messages as in the original post.

Has anyone had similar experiences using Raspberry Pi and possibly found any workarounds? I have a raspberry pi 4 at the office I could borrow to see if that helps perhaps. I think it's a 3B I have, not 3B+, so there is a different chip in the 3B+/4 I think.

**Comment by SweVictor** [comment]
I'm closing this since some issues seem to be solved and the original posted never got back.

Regarding the RPI issues in the last post, I suggest looking at other threads discussing similar issues and potentially chiming in there.
