### ISSUE TITLE
BLE Connection lost after some time and can't be reestablished.

### ISSUE THREAD

**Issue by richardsorensson** [icanos/hassio-plejd#239]
It seems as the Bluetooth connection is lost after a few days and it can't be re-established.

The only way to get it to re-established is to restart the plejd add-on, and it works for a few days again before the same issue appear again.

This is from the log, and the same is repeated all over.

2022-05-14 10:47:42 VRB [plejd-ble] Reconnect: Clean up, emit reconnect event, wait 5s and the re-init...
2022-05-14 10:47:42 VRB [plejd-ble] cleanup() - Clearing ping interval and clock update timer
2022-05-14 10:47:42 VRB [plejd-ble] Removing listeners to write events, bus events and objectManager...
2022-05-14 10:47:42 VRB [plejd-ble] Reconnect attempt 17078 in a row. Will power cycle every 10th time.
2022-05-14 10:47:42 INF [device-comm] Bluetooth reconnecting...
2022-05-14 10:47:42 VRB [device-comm] Stopping writeQueue loop until connection is established. Write queue length: 0
2022-05-14 10:47:47 INF [plejd-ble] Reconnecting BLE...
2022-05-14 10:47:47 INF [plejd-ble] init()
2022-05-14 10:47:47 VRB [plejd-ble] Managed paths[
  "/org/bluez",
  "/org/bluez/hci0",
  "/org/bluez/hci0/dev_E0_C2_4D_7C_2D_6C",
  "/org/bluez/hci0/dev_E0_96_63_4B_39_0A",
  "/org/bluez/hci0/dev_E6_60_6C_F0_80_0F",
  "/org/bluez/hci0/dev_D8_E3_17_2F_BC_97",
  "/org/bluez/hci0/dev_CF_51_62_C7_14_79"
]
2022-05-14 10:47:47 DBG [plejd-ble] Found BLE interface 'org.bluez.Adapter1' at /org/bluez/hci0
2022-05-14 10:47:47 VRB [plejd-ble] Powering on BLE adapter and waiting 5 seconds
2022-05-14 10:47:52 VRB [plejd-ble] Iterating 7 BLE managedObjects looking for org.bluez.Device1
2022-05-14 10:47:52 VRB [plejd-ble] Found /org/bluez/hci0/dev_E0_C2_4D_7C_2D_6C
2022-05-14 10:47:52 VRB [plejd-ble] Removing /org/bluez/hci0/dev_E0_C2_4D_7C_2D_6C from adapter.
2022-05-14 10:47:52 VRB [plejd-ble] Found /org/bluez/hci0/dev_E0_96_63_4B_39_0A
2022-05-14 10:47:52 VRB [plejd-ble] Removing /org/bluez/hci0/dev_E0_96_63_4B_39_0A from adapter.
2022-05-14 10:47:52 VRB [plejd-ble] Found /org/bluez/hci0/dev_E6_60_6C_F0_80_0F
2022-05-14 10:47:52 VRB [plejd-ble] Removing /org/bluez/hci0/dev_E6_60_6C_F0_80_0F from adapter.
2022-05-14 10:47:52 VRB [plejd-ble] Found /org/bluez/hci0/dev_D8_E3_17_2F_BC_97
2022-05-14 10:47:52 VRB [plejd-ble] Removing /org/bluez/hci0/dev_D8_E3_17_2F_BC_97 from adapter.
2022-05-14 10:47:52 VRB [plejd-ble] Found /org/bluez/hci0/dev_CF_51_62_C7_14_79
2022-05-14 10:47:52 VRB [plejd-ble] Removing /org/bluez/hci0/dev_CF_51_62_C7_14_79 from adapter.
2022-05-14 10:47:52 VRB [plejd-ble] All active BLE device connections cleaned up.
2022-05-14 10:47:52 VRB [plejd-ble] Got adapter undefined
2022-05-14 10:47:52 VRB [plejd-ble] Setting up interfacesAdded subscription and discovery filter
2022-05-14 10:47:52 VRB [plejd-ble] Starting BLE discovery... This can take up to 180 seconds.
2022-05-14 10:47:52 ERR [plejd-ble] Failed to start discovery. Operation already in progress
DBusError: Operation already in progress
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2022-05-14 10:47:52 INF [plejd-ble] If you continue to get "operation already in progress" error, you can try power cycling the bluetooth adapter. Get root console access, run "bluetoothctl" => "power off" => "power on" => "exit" => restart addon.
2022-05-14 10:47:52 WRN [plejd-ble] Failed reconnecting. Failed to start discovery. Make sure no other add-on is currently scanning.
Error: Failed to start discovery. Make sure no other add-on is currently scanning.
    at PlejBLEHandler._startGetPlejdDevice (/plejd/PlejdBLEHandler.js:436:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2022-05-14 10:47:52 VRB [plejd-ble] Reconnect: Clean up, emit reconnect event, wait 5s and the re-init...
2022-05-14 10:47:52 VRB [plejd-ble] cleanup() - Clearing ping interval and clock update timer

**Comment by bm500** [comment]
I have the same issue. The strange thing is that it has been working good for a very long time. But now I have an issue without changing anything (no updated done i HA).

**Comment by OaksHenrik** [comment]
Hi, I also have this problem. Do we have a solution?

**Comment by SweVictor** [comment]
There are many threads around this - some have found solutions some not.

If you have tried most things in the debugging section of the readme I don't know what to add personally. For me the BLE connection is stable with the latest versions. When fiddling a lot I sometimes needed to power cycle the computer (or VM).

I think my problems were mostly related to forwarding the USB stick from the host to the client VM though, so not necessarily related. In general you can see stuff with bluetoothctl and other built-in tools, but I don't know Linux well enough to help unfortunately.

**Comment by SweVictor** [comment]
Reporting back since I had some BLE issues myself. Found myself in a similar infinite reconnect loop. I tried the following steps
* Restart addon => Same issue
* Tried running various `bluetoothctl` commands (`power off` / `power on`). Got "Failed, controller busy" errors, couldn't run any commands at all. => Same issue in addon
* Restarted VM (I'm running this inside Windows) => Same issue
* Restarted entire host machine => Same issue (!)
* Plugged out the BT dongle and back in. Might have restarted VM or host, don't remember => SOLVED!

So - for me in this specific instance the actual BT dongle needed to be power cycled to alleviate the issue. Really unfortunate (to me) for a system that should be headless and run day after day...

Maybe someone with better Linux skills could have worked it out using only software/commands but I couldn't.

**Comment by OaksHenrik** [comment]
Mine started to work the other week, now when I think about it, it was around when we had some electrical work done in the house. (the main power was disconected).

Maybe it has the same effect as just remove and insert the dongel?

**Comment by lissmeister** [comment]
I've also had to power cycle the bt-dongle by unplugging it and that resolved it.

Maybe we could use `uhubctl` to control the power of the usb port, depending on platform. https://github.com/mochipon/hassio-uhubctl

I haven't tried this solution myself yet, but it looks promising.

**Comment by SweVictor** [comment]
A mini-update from me after running some more tests:

The addon actually supports removing and adding the BLE adapter during run, so no need to restart anything at all. It also supports adding the BLE adapter after the addon has started since it enumerates available devices every retry (and also resets everything it can every 10th retry).

**Comment by SweVictor** [comment]
Closing due to inactivity
