### ISSUE TITLE
404 from cloud login

### ISSUE THREAD

**Issue by ikke-t** [icanos/hassio-plejd#241]
Hi,

I tried setting up plejd on raspi3, and got stuck at this after configuring and restarting plejd:

```
2022-07-23 10:12:23 DBG [plejd-api] sending POST to https://cloud.plejd.com/parse/login
2022-07-23 10:12:24 ERR [plejd-api] Unable to retrieve session token response:  Request failed with status code 404
Error: Request failed with status code 404
    at createError (/plejd/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/plejd/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/plejd/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2022-07-23 10:12:24 ERR [plejd-api] Api request failed, no cached fallback available Converting circular structure to JSON
```

I have checked my credentials from gui and yaml, they are fine. This is what configs looks like:

```
site: Mökki
username: foo@bar.com
password: hidd3n*&secret
mqttBroker: mqtt://localhost
mqttUsername: secret-user
mqttPassword: secret
includeRoomsAsLights: false
preferCachedApiResponse: false
updatePlejdClock: true
logLevel: debug
connectionTimeout: 2
writeQueueWaitTime: 400
```

Any ideas? The internet from raspi should work fine, as ha succesfully updated several components, and installed and built plejd. Also time seems to be ok.

**Comment by ikke-t** [comment]
Looking at the code, could the appid have changed? If creds were wrong, it would return 403 I assume.

**Comment by ikke-t** [comment]
Sorry for the noise. I had likely something wrong with pwd. I reset my pwd and it works now. I wonder why the return code could was 404?
