### ISSUE TITLE
[plejd-mqtt] Initializing MQTT connection for Plejd addon

### ISSUE THREAD

**Issue by nicolaihc** [icanos/hassio-plejd#262]
Hello,

And thansk for making this Add-on :)

This is my first time running this addon. And i get a error so i cannot see my Plejd-units.

Is it the MQTT config that is not right? I have tryed to change mqtt-broker without any luck.

2022-12-13 13:07:07 INF [plejd-mqtt] Initializing MQTT connection for Plejd addon
Catastrophic error. Resetting entire addon in 1 minute Error: Missing protocol
    at Object.connect (/plejd/node_modules/mqtt/lib/connect/index.js:71:13)
    at MqttClient.init (/plejd/MqttClient.js:151:24)
    at PlejdAddon.init (/plejd/PlejdAddon.js:124:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/plejd/main.js:18:5)

**Comment by nicolaihc** [comment]
At last i got the MQTT working. But now i got a new problem. 
I think i maybe need to get the Bluetooth closer to my Plejd units?

WRN [plejd-ble] Unable to connect.  le-connection-abort-by-local
DBusError: le-connection-abort-by-local

**Comment by telcopro** [comment]
> Hello,
> 
> And thansk for making this Add-on :)
> 
> This is my first time running this addon. And i get a error so i cannot see my Plejd-units.
> 
> Is it the MQTT config that is not right? I have tryed to change mqtt-broker without any luck.
> 
> 2022-12-13 13:07:07 INF [plejd-mqtt] Initializing MQTT connection for Plejd addon Catastrophic error. Resetting entire addon in 1 minute Error: Missing protocol at Object.connect (/plejd/node_modules/mqtt/lib/connect/index.js:71:13) at MqttClient.init (/plejd/MqttClient.js:151:24) at PlejdAddon.init (/plejd/PlejdAddon.js:124:21) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async main (/plejd/main.js:18:5)



> Hello,
> 
> And thansk for making this Add-on :)
> 
> This is my first time running this addon. And i get a error so i cannot see my Plejd-units.
> 
> Is it the MQTT config that is not right? I have tryed to change mqtt-broker without any luck.
> 
> 2022-12-13 13:07:07 INF [plejd-mqtt] Initializing MQTT connection for Plejd addon Catastrophic error. Resetting entire addon in 1 minute Error: Missing protocol at Object.connect (/plejd/node_modules/mqtt/lib/connect/index.js:71:13) at MqttClient.init (/plejd/MqttClient.js:151:24) at PlejdAddon.init (/plejd/PlejdAddon.js:124:21) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async main (/plejd/main.js:18:5)

@nicolaihc Could you describe how you solved the protocol problem? I'm having the same and no idea how to change my MQTT URI.
