### ISSUE TITLE
Used to work, can't find suitable bt device

### ISSUE THREAD

**Issue by ikke-t** [icanos/hassio-plejd#263]
Hi,

this addon used to handle our lights ok, but now on the very same rpi3 install it can't get hold of bt device:

```
2023-01-07 22:36:47 INF [device-comm] Bluetooth reconnecting...
2023-01-07 22:36:52 INF [plejd-ble] Reconnecting BLE...
2023-01-07 22:36:52 INF [plejd-ble] init()
2023-01-07 22:36:52 DBG [plejd-ble] Found BLE interface 'org.bluez.Adapter1' at /org/bluez/hci0
2023-01-07 22:36:53 ERR [plejd-ble] Failed to get interface 'org.bluez.Adapter1'. 
DBusError
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2023-01-07 22:36:53 ERR [plejd-ble] Unable to find a bluetooth adapter that is compatible.
2023-01-07 22:36:53 WRN [plejd-ble] Failed reconnecting. Unable to find a bluetooth adapter that is compatible.
Error: Unable to find a bluetooth adapter that is compatible.
    at PlejBLEHandler._getInterface (/plejd/PlejdBLEHandler.js:356:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2023-01-07 22:36:53 INF [device-comm] Bluetooth reconnecting...
2023-01-07 22:36:58 INF [plejd-ble] Reconnecting BLE...
2023-01-07 22:36:58 INF [plejd-ble] init()
```

```
➜  ~ sudo bluetoothctl list
Controller B8:27:EB:B2:24:CA homeassistant [default]
```
```
2023-01-07 22:49:33 WRN [plejd-ble] Tried reconnecting 760 times. Will power cycle the BLE adapter now...
```

I have updated hassio several times remotely, but now while visiting the house, plejd didn't work any longer. The new Hassio bluetooth addon is disabled.

Any ideas?

**Comment by SWEiNSANE** [comment]
I have the very same problem on my Raspberry Pi 4 8GB running Home Assistant 2023.5.3, Supervisor 2023.04.1, Operating System 10.1. It used to work but for some time now the integrated bluetooth adapter cannot be found

2023-05-15 16:26:25 ERR [plejd-ble] Unable to find a bluetooth adapter that is compatible.
2023-05-15 16:26:25 WRN [plejd-ble] Failed reconnecting. Unable to find a bluetooth adapter that is compatible.
Error: Unable to find a bluetooth adapter that is compatible.
    at PlejBLEHandler._getInterface (/plejd/PlejdBLEHandler.js:356:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2023-05-15 16:26:25 INF [device-comm] Bluetooth reconnecting...
2023-05-15 16:26:30 INF [plejd-ble] Reconnecting BLE...
2023-05-15 16:26:30 INF [plejd-ble] init()
2023-05-15 16:26:30 ERR [plejd-ble] Failed to get interface 'org.bluez.Adapter1'. 
DBusError
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2023-05-15 16:26:30 ERR [plejd-ble] Unable to find a bluetooth adapter that is compatible.
2023-05-15 16:26:30 WRN [plejd-ble] Failed reconnecting. Unable to find a bluetooth adapter that is compatible.
Error: Unable to find a bluetooth adapter that is compatible.
    at PlejBLEHandler._getInterface (/plejd/PlejdBLEHandler.js:356:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2023-05-15 16:26:30 INF [device-comm] Bluetooth reconnecting...

**Comment by SweVictor** [comment]
If we don't get any Plejd adapters from the underlying infrastructure we can't do much. 

Anyone with RPI3/RPI4 that uses this addon that can pitch in? 

You could potentially also look at issues for other users using the same underlying library (search for dbus-next and bluez). I don't have much to suggest personally, unfortunately.
