### ISSUE TITLE
0.2.1 broken?

### ISSUE THREAD

**Issue by dennisgranasen** [icanos/hassio-plejd#27]
the Add-on does is not able to interact with my entities anymore. It all started with the update to 0.2.1 (which coincides with the launch of the ga functionality in the Plejd GW, so perhaps there's an update on plejd side of things that breaks it all?). 

The log says the following:
```
[10:46:56] INFO: Running add-on
starting Plejd add-on v. 0.2.0
plejd-api: got session token response
plejd-api: got sites response
wireEvents()
plejd-mqtt: connected to mqtt.
discovered light: Taklampa with Plejd ID 11.
discovered light: Spotlights with Plejd ID 12.
undefined:1
online
^
SyntaxError: Unexpected token o in JSON at position 0
    at JSON.parse (<anonymous>)
    at MqttClient.client.on (/plejd/mqtt.js:96:28)
    at MqttClient.emit (events.js:198:13)
    at MqttClient._handlePublish (/plejd/node_modules/mqtt/lib/client.js:1162:12)
    at MqttClient._handlePacket (/plejd/node_modules/mqtt/lib/client.js:351:12)
    at work (/plejd/node_modules/mqtt/lib/client.js:283:12)
    at Writable.writable._write (/plejd/node_modules/mqtt/lib/client.js:294:5)
    at doWrite (/plejd/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/plejd/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/plejd/node_modules/readable-stream/lib/_stream_writable.js:334:11)
```

Note also that the add-on reports that it started v0.2.0 instead of 0.2.1, although I suppose that is just a typo.

**Comment by Nebuchanezzer** [comment]
I get the same error, running hassio on a rpi4.

**Comment by icanos** [comment]
I’ll look into this, let me get back to you :-)

**Comment by icanos** [comment]
I changed the payload that is sent to the Plejd add-on in 0.2.1 to support transitions etc. The payload received above looks like its the old format, could you please restart HA to rediscover the lights and get the correct config and try again?

**Comment by Nebuchanezzer** [comment]
Restarting hassio did not help, but rebooting the device fixed it.

**Comment by icanos** [comment]
Thanks for reporting back. Closing this issue as resolved.
