### ISSUE TITLE
Issues with connecting after restarting HA

### ISSUE THREAD

**Issue by jonathanalmstrom** [icanos/hassio-plejd#274]
I have issues when I restart the computer running HA with the plejd addon. It connects the bluetooth dongle (external) to virtual box but then it throws error codes when trying to connect to plejd.
After many reboots and pulling the bluetooth adapter in and out it starts working but I dont know what fixes the issue.
Now i rebooted again and the problem came back.
Does anyone know how to fix this so I can reboot the computer without this problem coming back?

2023-06-13 12:51:45 INF [device-comm] Bluetooth reconnecting...
2023-06-13 12:51:47 ERR [plejd-ble] Discovery timeout elapsed, no devices found. Starting reconnect loop...
2023-06-13 12:51:47 INF [plejd-ble] Starting reconnect loop...
2023-06-13 12:51:50 INF [plejd-ble] Reconnecting BLE...
2023-06-13 12:51:50 INF [plejd-ble] init()
2023-06-13 12:51:55 ERR [plejd-ble] Failed to start discovery. Operation already in progress
DBusError: Operation already in progress
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2023-06-13 12:51:55 INF [plejd-ble] If you continue to get "operation already in progress" error, you can try power cycling the bluetooth adapter. Get root console access, run "bluetoothctl" => "power off" => "power on" => "exit" => restart addon.
2023-06-13 12:51:55 WRN [plejd-ble] Failed reconnecting. Failed to start discovery. Make sure no other add-on is currently scanning.
Error: Failed to start discovery. Make sure no other add-on is currently scanning.
    at PlejBLEHandler._startGetPlejdDevice (/plejd/PlejdBLEHandler.js:436:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2023-06-13 12:51:55 INF [device-comm] Bluetooth reconnecting...
2023-06-13 12:51:57 ERR [plejd-ble] Discovery timeout elapsed, no devices found. Starting reconnect loop...
2023-06-13 12:51:57 INF [plejd-ble] Starting reconnect loop...
2023-06-13 12:51:59 INF [device-comm] Plejd got turn on command for Köksbord (FC13DF04CE08_0), brightness undefined
2023-06-13 12:52:00 INF [plejd-ble] Reconnecting BLE...
2023-06-13 12:52:00 INF [plejd-ble] init()
2023-06-13 12:52:05 INF [plejd-ble] BLE init done, waiting for devices.
2023-06-13 12:52:07 ERR [plejd-ble] Discovery timeout elapsed, no devices found. Starting reconnect loop...
2023-06-13 12:52:07 INF [plejd-ble] Starting reconnect loop...
2023-06-13 12:52:07 INF [device-comm] Bluetooth reconnecting...
2023-06-13 12:52:12 INF [plejd-ble] Reconnecting BLE...
2023-06-13 12:52:12 INF [plejd-ble] init()
2023-06-13 12:52:17 ERR [plejd-ble] Failed to start discovery. Operation already in progress
DBusError: Operation already in progress
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2023-06-13 12:52:17 INF [plejd-ble] If you continue to get "operation already in progress" error, you can try power cycling the bluetooth adapter. Get root console access, run "bluetoothctl" => "power off" => "power on" => "exit" => restart addon.
2023-06-13 12:52:17 WRN [plejd-ble] Failed reconnecting. Failed to start discovery. Make sure no other add-on is currently scanning.
Error: Failed to start discovery. Make sure no other add-on is currently scanning.
    at PlejBLEHandler._startGetPlejdDevice (/plejd/PlejdBLEHandler.js:436:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2023-06-13 12:52:17 INF [device-comm] Bluetooth reconnecting...
2023-06-13 12:52:19 ERR [plejd-ble] Discovery timeout elapsed, no devices found. Starting reconnect loop...
2023-06-13 12:52:19 INF [plejd-ble] Starting reconnect loop...

**Comment by gittan443** [comment]
I got this issue also. When I was running on unsupported (Ubuntu / Docker) this never happend. Migrated to supported platform HassOS, and now it happens all the time. I have to reboot often and reseat bluetooth adapter.

**Comment by Vonken** [comment]
I have the same issue. Restarting my Raspberry Pi usally works but have to do this now and then like after a power-outages.

**Comment by SweVictor** [comment]
New version out if you want to try to update to see if that helps. Otherwise the classic troubleshooting - trying to move the dongle closer, etc.
