### ISSUE TITLE
Unable to retrieve session token response:  Error code 404

### ISSUE THREAD

**Issue by henke321** [icanos/hassio-plejd#281]
Hi, I have installed the Hassio-plejd integration in HA for the first time, but I always run in to the same problem with error 404 as seen in logg below. Any suggestion what I have missed or what I have to change? The RI4 is only 2 meters away from the Plejd puck and I have double checked tha all password etc is correct. 

2023-08-19 16:07:53 INF [plejd-api] login()
2023-08-19 16:07:53 INF [plejd-api] logging into Höga10
2023-08-19 16:07:53 ERR [plejd-api] Unable to retrieve session token response:  Request failed with status code 404
Error: Request failed with status code 404
    at createError (/plejd/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/plejd/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/plejd/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2023-08-19 16:07:53 ERR [plejd-api] Api request failed, no cached fallback available Converting circular structure to JSON
    --> starting at object with constructor 'ClientRequest'
    |     property 'socket' -> object with constructor 'TLSSocket'
    --- property '_httpMessage' closes the circle
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ClientRequest'
    |     property 'socket' -> object with constructor 'TLSSocket'
    --- property '_httpMessage' closes the circle

**Comment by SweVictor** [comment]
Duplicate of #264
