### ISSUE TITLE
Site name containing ÅÄÖ

### ISSUE THREAD

**Issue by nixs64** [icanos/hassio-plejd#29]
Never got this to work before I changed Site entry in Plejds system to simple "Niklas" instead of "Niklas Sjöstedt" 
I did not get session from Plejd and app restarted.

**Comment by nixs64** [comment]
starting Plejd add-on v. 0.2.0
plejd-api: got session token response
plejd-api: got sites response
(node:22178) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at instance.post.then.catch (/plejd/api.js:105:111)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22178) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22178) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[02:10:28] INFO: Starting the Plejd service...
[02:10:28] INFO: Verified permissions on startup script
[02:10:28] INFO: Executing startup script
[02:10:28] INFO: Wrote plejd.json
[02:10:28] INFO: Running add-on
starting Plejd add-on v. 0.2.0

**Comment by nixs64** [comment]
Checked with renaming Site in Plejd App and ÅÄÖ in site name seems to be the problem.

**Comment by icanos** [comment]
Interesting and thanks for the find. I'll have a look at it.

**Comment by icanos** [comment]
That's interesting, I just created a new site, renamed it to "Mitt höm" and read that without issue from the API. What device and oeprating system are you using?

**Comment by nixs64** [comment]
Raspberry pi 3b
Hassio

Den mån 13 jan. 2020 19:32Marcus Westin <notifications@github.com> skrev:

**Comment by nixs64** [comment]
Also gets what's seems like a crash after some time,.

plejd: connected via bluetooth.
(node:378) MaxListenersExceededWarning: Possible EventEmitter memory
leak detected. 11 write listeners added. Use emitter.setMaxListeners()
to increase limit


This is what the log writes out.



Den mån 13 jan. 2020 21:10Niklas <nixs64@gmail.com> skrev:

**Comment by icanos** [comment]
Closing due to inactivity

**Comment by rock3r-swe** [comment]
I can confirm that there is still a problem with the letter ä
My Plejd site ends with "vägen 99" and I get this in the log:

plejd-api: logging into vägen 99
plejd-api: got session token response
plejd-api: getSites()
plejd-api: got site list response
plejd-api: error: failed to find a site named vägen 99
(node:13304) UnhandledPromiseRejectionWarning: failed to find a site named vägen 99
