### ISSUE TITLE
Problem with bluetooth connection

### ISSUE THREAD

**Issue by borcksimon** [icanos/hassio-plejd#293]
Hi 

I have had a problem a few days now, that I have tried to fix but with no results. 

An example, when I try to switch a light off it’s switches itself on again I ha but the light have the same status. 

In the log I see Bluetooth connection fails. 

Any ideas? I have had this setup in over a year with no problems, so the raspberry pi is not to far away or something like that… 

2023-10-22 09:09:32 INF [plejd-ble] Reconnecting BLE...
2023-10-22 09:09:32 INF [plejd-ble] init()
2023-10-22 09:09:38 ERR [plejd-ble] Failed to start discovery. Operation already in progress
DBusError: Operation already in progress
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2023-10-22 09:09:38 INF [plejd-ble] If you continue to get "operation already in progress" error, you can try power cycling the bluetooth adapter. Get root console access, run "bluetoothctl" => "power off" => "power on" => "exit" => restart addon.
2023-10-22 09:09:38 WRN [plejd-ble] Failed reconnecting. Failed to start discovery. Make sure no other add-on is currently scanning.
Error: Failed to start discovery. Make sure no other add-on is currently scanning.
    at PlejBLEHandler._startGetPlejdDevice (/plejd/PlejdBLEHandler.js:445:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2023-10-22 09:09:38 WRN [plejd-ble] Tried reconnecting 10 times. Will power cycle the BLE adapter now...
2023-10-22 09:09:40 ERR [plejd-ble] Discovery timeout elapsed, no devices found. Starting reconnect loop...
2023-10-22 09:09:40 INF [plejd-ble] Starting reconnect loop...
2023-10-22 09:10:13 INF [device-comm] Bluetooth reconnecting...
2023-10-22 09:10:18 INF [plejd-ble] Reconnecting BLE...
2023-10-22 09:10:18 INF [plejd-ble] init()
2023-10-22 09:10:23 INF [plejd-ble] BLE init done, waiting for devices.
2023-10-22 09:10:25 INF [plejd-ble] Device discovery done, found 1 Plejd devices
2023-10-22 09:10:25 INF [plejd-ble] Connecting to /org/bluez/hci0/dev_FA_EF_C5_6B_0A_21
2023-10-22 09:10:36 INF [plejd-ble] onDeviceConnected()
2023-10-22 09:10:36 INF [plejd-ble] Connected to Plejd device Julstjärna  (FAEFC56B0A21, BLE id 41).
2023-10-22 09:10:36 INF [plejd-ble] authenticate()
2023-10-22 09:10:36 INF [plejd-ble] BLE Connected to Julstjärna 
2023-10-22 09:10:36 INF [plejd-ble] Requesting current Plejd time...
2023-10-22 09:10:36 INF [plejd-ble] startPing()
2023-10-22 09:10:36 INF [device-comm] Bluetooth connected. Plejd BLE up and running!
2023-10-22 09:10:36 INF [device-comm] startWriteQueue()
2023-10-22 09:11:06 WRN [plejd-ble] Plejd clock time off by more than 1 minute. Reported time: Sun Oct 22 2023 08:15:15 GMT+0200 (Central European Summer Time), diff -3352 seconds. Time will be set hourly.
2023-10-22 09:11:51 WRN [plejd-ble] Write error indicates BLE is disconnected. Retry count 5. Reconnecting...
2023-10-22 09:11:51 INF [plejd-ble] Starting reconnect loop...
2023-10-22 09:11:51 INF [device-comm] Bluetooth reconnecting...
2023-10-22 09:11:56 INF [plejd-ble] Reconnecting BLE...
2023-10-22 09:11:56 INF [plejd-ble] init()
2023-10-22 09:12:01 INF [plejd-ble] disconnecting /org/bluez/hci0/dev_FA_EF_C5_6B_0A_21. This can take up to 180 seconds
2023-10-22 09:12:04 ERR [plejd-ble] 'Unlikely error' (0x0e) writing to Plejd. Will retry. Operation failed with ATT error: 0x0e
DBusError: Operation failed with ATT error: 0x0e
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2023-10-22 09:12:04 INF [plejd-ble] BLE init done, waiting for devices.
2023-10-22 09:12:06 INF [plejd-ble] Device discovery done, found 1 Plejd devices
2023-10-22 09:12:06 INF [plejd-ble] Connecting to /org/bluez/hci0/dev_FB_F3_C6_CD_BF_54
2023-10-22 09:12:17 INF [plejd-ble] onDeviceConnected()
2023-10-22 09:12:17 INF [plejd-ble] Connected to Plejd device Murstock (FBF3C6CDBF54, BLE id 28).
2023-10-22 09:12:17 INF [plejd-ble] authenticate()
2023-10-22 09:12:17 INF [plejd-ble] BLE Connected to Murstock
2023-10-22 09:12:17 INF [plejd-ble] Requesting current Plejd time...
2023-10-22 09:12:17 INF [plejd-ble] startPing()
2023-10-22 09:12:17 INF [device-comm] Bluetooth connected. Plejd BLE up and running!
2023-10-22 09:12:17 INF [device-comm] startWriteQueue()
2023-10-22 09:13:42 WRN [plejd-ble] Plejd clock time off by more than 1 minute. Reported time: Sun Oct 22 2023 08:17:51 GMT+0200 (Central European Summer Time), diff -3352 seconds. Time will be set hourly.
2023-10-22 09:14:18 ERR [plejd-ble] 'Unlikely error' (0x0e) writing to Plejd. Will retry. Operation failed with ATT error: 0x0e
DBusError: Operation failed with ATT error: 0x0e
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2023-10-22 09:14:20 ERR [plejd-ble] 'Not connected' writing to Plejd. Plejd device is probably disconnected.
2023-10-22 09:14:20 WRN [plejd-ble] Write error indicates BLE is disconnected. Retry count 3. Reconnecting...
2023-10-22 09:14:20 INF [plejd-ble] Starting reconnect loop...
2023-10-22 09:14:20 INF [device-comm] Bluetooth reconnecting...
2023-10-22 09:14:25 INF [plejd-ble] Reconnecting BLE...
2023-10-22 09:14:25 INF [plejd-ble] init()
2023-10-22 09:14:30 INF [plejd-ble] BLE init done, waiting for devices.
2023-10-22 09:14:32 ERR [plejd-ble] Uh oh, no Plejd device!
2023-10-22 09:14:32 INF [plejd-ble] Device discovery done, found 1 Plejd devices
2023-10-22 09:14:32 INF [plejd-ble] Connecting to /org/bluez/hci0/dev_C5_0F_0D_20_4F_23
2023-10-22 09:14:b45 INF [plejd-ble] onDeviceConnected()
2023-10-22 09:14:45 INF [plejd-ble] Connected to Plejd device Smygspott (C50F0D204F23, BLE id 44).
2023-10-22 09:14:45 INF [plejd-ble] authenticate()
2023-10-22 09:14:45 INF [plejd-ble] BLE Connected to Smygspott
2023-10-22 09:14:45 INF [plejd-ble] Requesting current Plejd time...
2023-10-22 09:14:45 INF [plejd-ble] startPing()
2023-10-22 09:14:45 INF [device-comm] Bluetooth connected. Plejd BLE up and running!
2023-10-22 09:14:45 INF [device-comm] startWriteQueue()
2023-10-22 09:17:15 WRN [plejd-ble] Write error indicates BLE is disconnected. Retry count 5. Reconnecting...
2023-10-22 09:17:15 INF [plejd-ble] Starting reconnect loop...
2023-10-22 09:17:15 INF [device-comm] Bluetooth reconnecting...
2023-10-22 09:17:20 INF [plejd-ble] Reconnecting BLE...
2023-10-22 09:17:20 INF [plejd-ble] init()I’m

**Comment by Wronek** [comment]
Hello, propably I have the same issue. When I press turn on lamp physicaly light on but state return to off. 
Log below:

2023-10-22 11:20:57 INF [plejd-ble] BLE init done, waiting for devices.
2023-10-22 11:20:57 INF [plejd-main] Main init done
2023-10-22 11:20:57 INF [plejd-main] main() finished
2023-10-22 11:20:59 INF [plejd-ble] Device discovery done, found 1 Plejd devices
2023-10-22 11:20:59 INF [plejd-ble] Connecting to /org/bluez/hci0/dev_DC_7A_9C_B5_F9_6D
2023-10-22 11:21:02 INF [plejd-ble] onDeviceConnected()
2023-10-22 11:21:02 INF [plejd-ble] Connected to Plejd device Dimmer (DC7A9CB5F96D, BLE id 11).
2023-10-22 11:21:02 INF [plejd-ble] authenticate()
2023-10-22 11:21:02 INF [plejd-ble] BLE Connected to Dimmer
2023-10-22 11:21:02 INF [plejd-ble] Plejd clock updates disabled in configuration.
2023-10-22 11:21:02 INF [plejd-ble] startPing()
2023-10-22 11:21:02 INF [device-comm] Bluetooth connected. Plejd BLE up and running!
2023-10-22 11:21:02 INF [device-comm] startWriteQueue()
2023-10-22 11:21:23 INF [device-comm] Plejd got turn on command for Dimmer (DC7A9CB5F96D_0), brightness undefined
2023-10-22 11:21:30 INF [device-comm] Plejd got turn on command for Dimmer (DC7A9CB5F96D_0), brightness 181
2023-10-22 11:21:31 INF [device-comm] Plejd got turn on command for Dimmer (DC7A9CB5F96D_0), brightness 255
2023-10-22 11:21:35 INF [device-comm] Plejd got turn on command for Dimmer (DC7A9CB5F96D_0), brightness undefined
2023-10-22 11:21:37 INF [device-comm] Plejd got turn on command for Dimmer (DC7A9CB5F96D_0), brightness 181
2023-10-22 11:21:38 INF [device-comm] Plejd got turn on command for Dimmer (DC7A9CB5F96D_0), brightness undefined
2023-10-22 11:21:38 INF [device-comm] Plejd got turn on command for Dimmer (DC7A9CB5F96D_0), brightness undefined
2023-10-22 11:21:38 INF [device-comm] Plejd got turn on command for Dimmer (DC7A9CB5F96D_0), brightness undefined
2023-10-22 11:21:39 INF [device-comm] Plejd got turn on command for Dimmer (DC7A9CB5F96D_0), brightness undefined
2023-10-22 11:21:39 INF [device-comm] Plejd got turn on command for Dimmer (DC7A9CB5F96D_0), brightness undefined
2023-10-22 11:21:40 INF [device-comm] Plejd got turn on command for Dimmer (DC7A9CB5F96D_0), brightness 3
2023-10-22 11:21:42 INF [device-comm] Plejd got turn on command for Dimmer (DC7A9CB5F96D_0), brightness 255
2023-10-22 11:21:50 WRN [plejd-ble] Write error indicates BLE is disconnected. Retry count 5. Reconnecting...
2023-10-22 11:21:50 INF [plejd-ble] Starting reconnect loop...
2023-10-22 11:21:50 INF [device-comm] Bluetooth reconnecting...
2023-10-22 11:21:55 INF [plejd-ble] Reconnecting BLE...
2023-10-22 11:21:55 INF [plejd-ble] init()
2023-10-22 11:22:00 INF [plejd-ble] disconnecting /org/bluez/hci0/dev_DC_7A_9C_B5_F9_6D. This can take up to 180 seconds
2023-10-22 11:22:02 ERR [plejd-ble] 'Unlikely error' (0x0e) writing to Plejd. Will retry. Operation failed with ATT error: 0x0e
DBusError: Operation failed with ATT error: 0x0e
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2023-10-22 11:22:02 ERR [plejd-ble] 'Unlikely error' (0x0e) writing to Plejd. Will retry. Operation failed with ATT error: 0x0e
DBusError: Operation failed with ATT error: 0x0e
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2023-10-22 11:22:02 WRN [device-comm] BLE not connected, stopping write queue until connection is up again.
2023-10-22 11:22:03 INF [plejd-ble] BLE init done, waiting for devices.
2023-10-22 11:22:05 INF [plejd-ble] Device discovery done, found 1 Plejd devices
2023-10-22 11:22:05 INF [plejd-ble] Connecting to /org/bluez/hci0/dev_DC_7A_9C_B5_F9_6D
2023-10-22 11:22:07 INF [plejd-ble] onDeviceConnected()
2023-10-22 11:22:07 INF [plejd-ble] Connected to Plejd device Dimmer (DC7A9CB5F96D, BLE id 11).
2023-10-22 11:22:07 INF [plejd-ble] authenticate()
2023-10-22 11:22:07 INF [plejd-ble] BLE Connected to Dimmer
2023-10-22 11:22:07 INF [plejd-ble] Plejd clock updates disabled in configuration.
2023-10-22 11:22:07 INF [plejd-ble] startPing()
2023-10-22 11:22:07 INF [device-comm] Bluetooth connected. Plejd BLE up and running!
2023-10-22 11:22:07 INF [device-comm] startWriteQueue()
2023-10-22 11:23:52 WRN [plejd-ble] Write error indicates BLE is disconnected. Retry count 5. Reconnecting...
2023-10-22 11:23:52 INF [plejd-ble] Starting reconnect loop...
2023-10-22 11:23:52 INF [device-comm] Bluetooth reconnecting...

**Comment by ChanceGPM** [comment]
Same issue for me. The light stays of in home assistant but it turns on irl

**Comment by borcksimon** [comment]
I have tried a few things but with no good results.. 

1. A simple reset ofc 

2. Restored both Plejd, mqtt, and ha to previous versions

3. And also a complete reinstallation of all the integrations

**Comment by albinsito** [comment]
Same issue for me as well. This actually started sometime earlier this summer. Have tried same above.

**Comment by f00dagi** [comment]
I have the same issue. This add-on has been really valuable the last couple of years, I hope there is a way to solve this issue. Thanks for your efforts.

**Comment by Minglarn** [comment]
Hmmm... Having the same issues...
Did remove the plejd addon and reinstalled it... no diff. 
As mentioned in a couple of comments above... 
The lights stays of in HAS but turns on IRL, and I think that this slows down the H.A a lot.
Do not see any issues with the B.T dongle as it works flawless with other BT devices... No interruptions there.. 

![image](https://github.com/icanos/hassio-plejd/assets/58695742/1fe8c7ed-f504-4aa0-80ba-6908e74b1684)
![image](https://github.com/icanos/hassio-plejd/assets/58695742/b78d638c-3872-4682-aa12-ba79d39c3974)

**Comment by SweVictor** [comment]
Just making sure everyone is aware that there are known bugs with the latest HAOS version? IF you have upgraded I would say the issues described here are expected

https://github.com/icanos/hassio-plejd/issues/292

/Victor

**Comment by SweVictor** [comment]
Noting that #292 was fixed by installing the beta HAOS 11.0.RC1. So do try that fix if you're still having issues. A few terminal commands, quite easy to do.

**Comment by borcksimon** [comment]
ha os update --version 10.5 worked for me. 
Thank you SweVictor!

**Comment by supercrw** [comment]
Anyone upgraded to HAOS 11.1 yet?

**Comment by T3KPCS7** [comment]
> Anyone upgraded to HAOS 11.1 yet?

Yes, and everything seems to be working fine again for me

**Comment by eriktiekstra** [comment]
> Anyone upgraded to HAOS 11.1 yet?

Yes, I still have issues. Not sure if it is the same type of issue though?
`2023-10-31 11:46:46 ERR [plejd-ble] Error handling /org/bluez/hci1/dev_EE_AC_45_BF_0B_19 Does Not Exist
DBusError: Does Not Exist
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2023-10-31 11:46:46 ERR [plejd-ble] Error handling /org/bluez/hci1/dev_61_96_97_C0_C5_E5 Does Not Exist
DBusError: Does Not Exist
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2023-10-31 11:46:46 ERR [plejd-ble] Error handling /org/bluez/hci1/dev_6F_C6_8F_85_92_47 Does Not Exist
DBusError: Does Not Exist
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2023-10-31 11:46:46 ERR [plejd-ble] Error handling /org/bluez/hci1/dev_C6_58_5E_1B_C2_A2 Does Not Exist
DBusError: Does Not Exist
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2023-10-31 11:46:46 ERR [plejd-ble] Error handling /org/bluez/hci1/dev_7C_87_CE_58_2B_3A Does Not Exist
DBusError: Does Not Exist
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2023-10-31 11:46:46 ERR [plejd-ble] Error handling /org/bluez/hci1/dev_C7_7F_53_2C_B4_D7 Does Not Exist
DBusError: Does Not Exist
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2023-10-31 11:46:46 ERR [plejd-ble] Error handling /org/bluez/hci1/dev_F3_F1_DC_C0_EA_E4 Does Not Exist
DBusError: Does Not Exist
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2023-10-31 11:46:46 ERR [plejd-ble] Failed to start discovery. Operation already in progress
DBusError: Operation already in progress
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2023-10-31 11:46:46 INF [plejd-ble] If you continue to get "operation already in progress" error, you can try power cycling the bluetooth adapter. Get root console access, run "bluetoothctl" => "power off" => "power on" => "exit" => restart addon.
2023-10-31 11:46:46 WRN [plejd-ble] Failed reconnecting. Failed to start discovery. Make sure no other add-on is currently scanning.
Error: Failed to start discovery. Make sure no other add-on is currently scanning.
    at PlejBLEHandler._startGetPlejdDevice (/plejd/PlejdBLEHandler.js:445:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2023-10-31 11:46:46 WRN [plejd-ble] Tried reconnecting 40 times. Will power cycle the BLE adapter now...
2023-10-31 11:46:48 ERR [plejd-ble] Discovery timeout elapsed, no devices found. Starting reconnect loop...
2023-10-31 11:46:48 INF [plejd-ble] Starting reconnect loop...`

**Comment by SweVictor** [comment]
Closing this as solved by the latest HAOS version.

@eriktiekstra (and others): If you continue to have issues after updating HA/HAOS and this addon to the latest versions, feel free to post a new issue after looking at similar ones. There are several old issues discussing BLE connectivity issues. If they don't help fix the problem please post a logs showing the startup flow during the setup phase in at least debug mode.
