### ISSUE TITLE
It has been working flawlessly for several years but now ...   Uh no , no Plejd device !!!     

### ISSUE THREAD

**Issue by stefancn** [icanos/hassio-plejd#302]
After upgrades of the HA,  Plejd addon doesnt work ... the only way to make work is a total power cycle, Then the Plejd addon works for another couple of hours. ..

Talked to my HA friends , all of them (three) have the
same problem ... so it is a bug somewhere

Can you please help us out there to find the cause of the error / bug.   

2024-05-23 09:42:57 INF [plejd-main] Log level set to info
Starting Plejd addon and reading configuration...
2024-05-23 09:42:57 INF [plejd-main] Log level set to info
2024-05-23 09:42:57 INF [plejd-main] Plejd add-on, version 0.11.0
2024-05-23 09:42:57 INF [device-comm] Starting Plejd communication handler.
2024-05-23 09:42:57 INF [plejd-ble] Starting Plejd BLE Handler, resetting all device states.
2024-05-23 09:42:57 INF [plejd-main] Main Plejd addon init()...
2024-05-23 09:42:57 INF [plejd-api] init()
2024-05-23 09:42:57 INF [plejd-api] Getting cached api response from disk
2024-05-23 09:42:57 INF [plejd-api] login()
2024-05-23 09:42:57 INF [plejd-api] logging into LDAB
2024-05-23 09:42:57 INF [plejd-api] got session token response
2024-05-23 09:42:57 INF [plejd-api] Get all Plejd sites for account...
2024-05-23 09:42:57 INF [plejd-api] Got site list response with 2: Elefanten4, LDAB
2024-05-23 09:42:58 INF [plejd-api] Site found matching configuration name LDAB
2024-05-23 09:42:58 INF [plejd-api] Get site details for c945a2f6-200a-44fc-8245-a60592fce61a...
2024-05-23 09:42:58 INF [plejd-api] got site details response
2024-05-23 09:42:58 INF [plejd-api] Site details for site id c945a2f6-200a-44fc-8245-a60592fce61a found
2024-05-23 09:42:58 INF [plejd-api] Saving cached copy
2024-05-23 09:42:58 INF [plejd-api] Getting devices from site details response...
2024-05-23 09:42:58 INF [plejd-api] Plejd gateway 'LDAB Lab' found on site
2024-05-23 09:42:58 INF [plejd-mqtt] Initializing MQTT connection for Plejd addon
2024-05-23 09:42:58 INF [plejd-ble] init()
2024-05-23 09:42:59 INF [plejd-mqtt] Connected to MQTT.
2024-05-23 09:42:59 INF [plejd-mqtt] Sending discovery for 17 Plejd output devices
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered DIM-02 (light) named FasadInneMexi (12 : DD5B4DA52EE8_1).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered DIM-02 (light) named Matsalsbord (11 : DD5B4DA52EE8_0).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered DIM-02 (light) named FasadBelSpa (14 : DC479EEFB217_0).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered DIM-02 (light) named Altanbel.Utsida (15 : DC479EEFB217_1).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered DIM-02 (light) named Bel_Lounge (16 : F33433A7B5F7_0).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered DIM-02 (light) named Spare (17 : F33433A7B5F7_1).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered CTR-01 (light) named Bel_Träd (21 : F5B03AD1ED5F_0).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered CTR-01 (light) named Utomhus Bod (22 : DDA5EF54FB99_0).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered CTR-01 (light) named Fasadbel. framsida (23 : E5638F2062E6_0).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered DIM-02 (light) named Kök Gångstråk (28 : D03235351DFF_0).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered DIM-02 (light) named Kök  (29 : D03235351DFF_1).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered DIM-02 (light) named Bel Köksbord (31 : EBDD574EB103_0).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered DIM-02 (light) named Fönsterbel. Diskbänk (34 : EBDD574EB103_1).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered CTR-01 (light) named Skåpsbel. Kök (33 : EC84092ABCD5_0).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered CTR-01 (switch) named Kamin (37 : C5A71909ED30_0).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered DIM-01 (light) named TakbelKupa (25 : E17187B41782_0).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered LED-10 (light) named Skåpsbelysning (26 : E52E8F932BA2_0).
2024-05-23 09:42:59 INF [plejd-mqtt] Sending discovery for 12 Plejd input devices
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named DörrTillUterun (19 : FB2670B1EFEE_I_0).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named DörrTillUterun (19 : FB2670B1EFEE_I_2).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named DörrTillUterun (19 : FB2670B1EFEE_I_1).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named DörrTillUterun (19 : FB2670B1EFEE_I_3).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named Kök från groventre (32 : DBB30CE3B6EF_I_0).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named Kök från groventre (32 : DBB30CE3B6EF_I_1).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named Kök från groventre (32 : DBB30CE3B6EF_I_2).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named Kök från groventre (32 : DBB30CE3B6EF_I_3).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named Till Kök från Hall (30 : FB704C638D49_I_0).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named Till Kök från Hall (30 : FB704C638D49_I_1).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named Till Kök från Hall (30 : FB704C638D49_I_2).
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered WPH-01 (device_automation) named Till Kök från Hall (30 : FB704C638D49_I_3).
2024-05-23 09:42:59 INF [plejd-mqtt] Sending discovery for 1 Plejd scene devices
2024-05-23 09:42:59 INF [plejd-mqtt] Discovered Scene (scene) named KöketUtomSkåo (9 : db6e51dc-ace8-48a1-8a4c-bc3501e2c51d).
2024-05-23 09:42:59 INF [device-comm] Plejd got turn on command for FasadInneMexi (DD5B4DA52EE8_1), brightness undefined
2024-05-23 09:42:59 INF [device-comm] Plejd got turn off command for Matsalsbord (DD5B4DA52EE8_0)
2024-05-23 09:42:59 INF [device-comm] Plejd got turn on command for Altanbel.Utsida (DC479EEFB217_1), brightness undefined
2024-05-23 09:42:59 INF [device-comm] Plejd got turn on command for FasadBelSpa (DC479EEFB217_0), brightness undefined
2024-05-23 09:42:59 INF [device-comm] Plejd got turn off command for Bel_Lounge (F33433A7B5F7_0)
2024-05-23 09:42:59 INF [device-comm] Plejd got turn off command for Spare (F33433A7B5F7_1)
2024-05-23 09:42:59 INF [device-comm] Plejd got turn off command for Bel_Träd (F5B03AD1ED5F_0)
2024-05-23 09:42:59 INF [device-comm] Plejd got turn on command for Utomhus Bod (DDA5EF54FB99_0), brightness undefined
2024-05-23 09:42:59 INF [device-comm] Plejd got turn on command for Fasadbel. framsida (E5638F2062E6_0), brightness undefined
2024-05-23 09:42:59 INF [device-comm] Plejd got turn on command for TakbelKupa (E17187B41782_0), brightness undefined
2024-05-23 09:42:59 INF [device-comm] Plejd got turn on command for Kök Gångstråk (D03235351DFF_0), brightness undefined
2024-05-23 09:42:59 INF [device-comm] Plejd got turn off command for Kök  (D03235351DFF_1)
2024-05-23 09:42:59 INF [device-comm] Plejd got turn off command for Bel Köksbord (EBDD574EB103_0)
2024-05-23 09:42:59 INF [device-comm] Plejd got turn on command for Fönsterbel. Diskbänk (EBDD574EB103_1), brightness 255
2024-05-23 09:42:59 INF [device-comm] Plejd got turn off command for Skåpsbel. Kök (EC84092ABCD5_0)
2024-05-23 09:42:59 WRN [plejd-mqtt] Device for topic homeassistant/light/plejd/E419BC8DB765_0/set not found! Can happen if HA calls previously existing devices.
2024-05-23 09:42:59 INF [device-comm] Plejd got turn on command for Skåpsbelysning (E52E8F932BA2_0), brightness 23
2024-05-23 09:42:59 INF [device-comm] Plejd got turn off command for Kamin (C5A71909ED30_0)
2024-05-23 09:43:06 ERR [plejd-ble] Discovery timeout elapsed, no devices found. Starting reconnect loop...
2024-05-23 09:43:06 INF [plejd-ble] Starting reconnect loop...
2024-05-23 09:43:06 INF [device-comm] Bluetooth reconnecting...
2024-05-23 09:43:11 INF [plejd-ble] Reconnecting BLE...
2024-05-23 09:43:11 INF [plejd-ble] init()
2024-05-23 09:43:16 ERR [plejd-ble] Failed to start discovery. Operation already in progress
DBusError: Operation already in progress
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2024-05-23 09:43:16 INF [plejd-ble] If you continue to get "operation already in progress" error, you can try power cycling the bluetooth adapter. Get root console access, run "bluetoothctl" => "power off" => "power on" => "exit" => restart addon.
2024-05-23 09:43:16 WRN [plejd-ble] Failed reconnecting. Failed to start discovery. Make sure no other add-on is currently scanning.
Error: Failed to start discovery. Make sure no other add-on is currently scanning.
    at PlejBLEHandler._startGetPlejdDevice (/plejd/PlejdBLEHandler.js:445:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2024-05-23 09:43:16 INF [device-comm] Bluetooth reconnecting...

**Comment by SweVictor** [comment]
Some BLE updates have happened inside HA and also some updates were pushed here yesterday. Hopefully, that fixes the problem.
