### ISSUE TITLE
Could not connect to any Plejd device. Starting reconnect loop...

### ISSUE THREAD

**Issue by FredrikVaaland** [icanos/hassio-plejd#305]
What is wrong? Any ideas?

at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2024-07-08 15:31:28 ERR [plejd-ble] Could not connect to any Plejd device. Starting reconnect loop...
2024-07-08 15:31:28 INF [plejd-ble] Starting reconnect loop...
2024-07-08 15:31:28 WRN [plejd-ble] Tried reconnecting 10 times. Will power cycle the BLE adapter now...
2024-07-08 15:32:03 INF [device-comm] Bluetooth reconnecting...
2024-07-08 15:32:08 INF [plejd-ble] Reconnecting BLE...
2024-07-08 15:32:08 INF [plejd-ble] init()
2024-07-08 15:32:13 INF [plejd-ble] BLE init done, waiting for devices.
2024-07-08 15:32:15 INF [plejd-ble] Device discovery done, found 1 Plejd devices
2024-07-08 15:32:15 INF [plejd-ble] Connecting to /org/bluez/hci0/dev_F7_2A_C5_DD_4E_FB
2024-07-08 15:32:16 WRN [plejd-ble] Unable to connect.  le-connection-abort-by-local
DBusError: le-connection-abort-by-local
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2024-07-08 15:32:16 ERR [plejd-ble] Could not connect to any Plejd device. Starting reconnect loop...
2024-07-08 15:32:16 INF [plejd-ble] Starting reconnect loop...
2024-07-08 15:32:16 INF [device-comm] Bluetooth reconnecting...
2024-07-08 15:32:21 INF [plejd-ble] Reconnecting BLE...
2024-07-08 15:32:21 INF [plejd-ble] init()
2024-07-08 15:32:26 INF [plejd-ble] BLE init done, waiting for devices.
2024-07-08 15:32:28 INF [plejd-ble] Device discovery done, found 1 Plejd devices
2024-07-08 15:32:28 INF [plejd-ble] Connecting to /org/bluez/hci0/dev_F7_2A_C5_DD_4E_FB
2024-07-08 15:32:29 WRN [plejd-ble] Unable to connect.  le-connection-abort-by-local
DBusError: le-connection-abort-by-local
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2024-07-08 15:32:29 ERR [plejd-ble] Could not connect to any Plejd device. Starting reconnect loop...
2024-07-08 15:32:29 INF [plejd-ble] Starting reconnect loop...
2024-07-08 15:32:29 INF [device-comm] Bluetooth reconnecting...
2024-07-08 15:32:34 INF [plejd-ble] Reconnecting BLE...
2024-07-08 15:32:34 INF [plejd-ble] init()
2024-07-08 15:32:39 INF [plejd-ble] BLE init done, waiting for devices.
2024-07-08 15:32:41 INF [plejd-ble] Device discovery done, found 1 Plejd devices
2024-07-08 15:32:41 INF [plejd-ble] Connecting to /org/bluez/hci0/dev_DE_A6_67_C0_13_1B
2024-07-08 15:32:42 WRN [plejd-ble] Unable to connect.  le-connection-abort-by-local
DBusError: le-connection-abort-by-local
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2024-07-08 15:32:42 ERR [plejd-ble] Could not connect to any Plejd device. Starting reconnect loop...
2024-07-08 15:32:42 INF [plejd-ble] Starting reconnect loop...
2024-07-08 15:32:42 INF [device-comm] Bluetooth reconnecting...
2024-07-08 15:32:47 INF [plejd-ble] Reconnecting BLE...
2024-07-08 15:32:47 INF [plejd-ble] init()
2024-07-08 15:32:53 INF [plejd-ble] BLE init done, waiting for devices.
2024-07-08 15:32:55 INF [plejd-ble] Device discovery done, found 1 Plejd devices
2024-07-08 15:32:55 INF [plejd-ble] Connecting to /org/bluez/hci0/dev_F7_2A_C5_DD_4E_FB
2024-07-08 15:32:56 WRN [plejd-ble] Unable to connect.  le-connection-abort-by-local
DBusError: le-connection-abort-by-local

**Comment by jn73** [comment]
I have exactly the same problem. Raspberry 5

**Comment by jn73** [comment]
Looks like it will connect eventually (usually after a couple of hours) if I just leave the add-on running.

**Comment by FredrikVaaland** [comment]
Im lost, any chance you can give me a short discription of your set up?

**Comment by jn73** [comment]
Sorry for the late reply :-( 

I've seen those logs also (DBusError: Operation already in progress) and the "Make sure no other add-on is currently scanning."-line.

Now I just restarted my Raspberry Pi 5 and seeing this:

```2024-09-04 21:09:47 ERR [plejd-ble] Could not connect to any Plejd device. Starting reconnect loop...
2024-09-04 21:09:47 INF [plejd-ble] Starting reconnect loop...
2024-09-04 21:09:47 INF [device-comm] Bluetooth reconnecting...
2024-09-04 21:09:52 INF [plejd-ble] Reconnecting BLE...
2024-09-04 21:09:52 INF [plejd-ble] init()
2024-09-04 21:09:57 INF [plejd-ble] BLE init done, waiting for devices.
2024-09-04 21:09:59 INF [plejd-ble] Device discovery done, found 1 Plejd devices
2024-09-04 21:09:59 INF [plejd-ble] Connecting to /org/bluez/hci0/dev_DD_ED_05_FB_B1_62
2024-09-04 21:09:59 WRN [plejd-ble] Unable to connect.  le-connection-abort-by-local
DBusError: le-connection-abort-by-local
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2024-09-04 21:09:59 ERR [plejd-ble] Could not connect to any Plejd device. Starting reconnect loop...
2024-09-04 21:09:59 INF [plejd-ble] Starting reconnect loop...
2024-09-04 21:09:59 WRN [plejd-ble] Tried reconnecting 320 times. Will power cycle the BLE adapter now...
2024-09-04 21:10:35 INF [device-comm] Bluetooth reconnecting...```

I'm  pretty sure it will reconnect within a few hours and then work fine until next restart.

My system is pretty basic. Raspberry Pi 5 and a SkyConnect (which shouldn't have anything to do with this).

**Comment by jn73** [comment]
I saw a log warning from the "Rasperry Pi Power Supply Checker" that my system is "Under-voltage". I checked it up and realize that i need a more powerful PSU. I ordered the standard rasperry adapter but haven't received it yet. Not really counting on this to fix it, but i read that it could have some impact on buses etc. Just thought i should point out that it wasn't the standard raspberry pi setup after all.
