### ISSUE TITLE
Looks like it detects my divices but i still get some errors

### ISSUE THREAD

**Issue by burymenot** [icanos/hassio-plejd#75]
So i installd the plejd app-adon and it looks like it detects my divices but i still get some errors in i can't find my devices in home assistant.

s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: Plejd
 Adds support for the Swedish home automation devices from Plejd.
-----------------------------------------------------------
 Add-on version: 0.4.3
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[10:43:09] ERROR: Unknown HTTP error occured
 System:   (amd64 / qemux86-64)
 Home Assistant version: 0.107.1
 Supervisor version: 209
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:43:09] INFO: Starting the Plejd service...
[10:43:09] INFO: Verified permissions on startup script
[10:43:09] INFO: Executing startup script
[10:43:09] INFO: Wrote plejd.json
[10:43:09] INFO: Running add-on
starting Plejd add-on v. 0.4.3
plejd-api: login()
plejd-api: logging into Svärdet
plejd-api: got session token response
plejd-api: getSites()
plejd-api: got site list response
plejd-api: getSites()
plejd-api: got site details response
wireEvents()
init()
(node:290) UnhandledPromiseRejectionWarning: DBusError: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender="(null)" (inactive) interface="org.freedesktop.DBus" member="Hello" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus)
    at _methodReturnHandlers.(anonymous function) (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:555:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:290) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:290) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (DIM-02) named Spotlight with PID 13.
plejd-mqtt: discovered light (DIM-02) named Taklampa with PID 14.
plejd-mqtt: discovered light (DIM-01) named Vardagsrum Öv with PID 11.
plejd-mqtt: discovered light (LED-10) named Smyg with PID 16.
plejd-mqtt: discovered light (DIM-01) named Spegel with PID 15.
plejd-mqtt: discovered switch (Scene) named Tänd på min with PID 1.
plejd-mqtt: discovered switch (Scene) named Släck VRÖ with PID 3.

**Comment by icanos** [comment]
Please try 0.4.4 which I published today, I've disabled AppArmor completely now.

**Comment by burymenot** [comment]
Ok thank you!
Now the errors are fixed. But i still can't find the devices. Is it supposed to show up in entities?

This is how my log look now 

[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:24:54] INFO: Starting the Plejd service...
[13:24:54] INFO: Verified permissions on startup script
[13:24:54] INFO: Executing startup script
[13:24:55] INFO: Wrote plejd.json
[13:24:55] INFO: Running add-on
starting Plejd add-on v. 0.4.4
plejd-api: login()
plejd-api: logging into Svärdet
plejd-api: got session token response
plejd-api: getSites()
plejd-api: got site list response
plejd-api: getSite(...)
plejd-api: got site details response
wireEvents()
init()
plejd-ble: disconnecting /org/bluez/hci0/dev_CA_EC_AD_75_97_05
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (DIM-02) named Spotlight with PID 13.
plejd-mqtt: discovered light (DIM-02) named Taklampa with PID 14.
plejd-mqtt: discovered light (DIM-01) named Vardagsrum Öv with PID 11.
plejd-mqtt: discovered light (LED-10) named Smyg with PID 16.
plejd-mqtt: discovered light (DIM-01) named Spegel with PID 15.
plejd-mqtt: discovered switch (Scene) named Tänd på min with PID 1.
plejd-mqtt: discovered switch (Scene) named Släck VRÖ with PID 3.
plejd-ble: connecting to /org/bluez/hci0/dev_CA_EC_AD_75_97_05
onDeviceConnected()
trying 10 characteristics
authenticate()
startPing()
startWriteQueue()
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (DIM-02) named Spotlight with PID 13.
plejd-mqtt: discovered light (DIM-02) named Taklampa with PID 14.
plejd-mqtt: discovered light (DIM-01) named Vardagsrum Öv with PID 11.
plejd-mqtt: discovered light (LED-10) named Smyg with PID 16.
plejd-mqtt: discovered light (DIM-01) named Spegel with PID 15.
plejd-mqtt: discovered switch (Scene) named Tänd på min with PID 1.
plejd-mqtt: discovered switch (Scene) named Släck VRÖ with PID 3.
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (DIM-02) named Spotlight with PID 13.
plejd-mqtt: discovered light (DIM-02) named Taklampa with PID 14.
plejd-mqtt: discovered light (DIM-01) named Vardagsrum Öv with PID 11.
plejd-mqtt: discovered light (LED-10) named Smyg with PID 16.
plejd-mqtt: discovered light (DIM-01) named Spegel with PID 15.
plejd-mqtt: discovered switch (Scene) named Tänd på min with PID 1.
plejd-mqtt: discovered switch (Scene) named Släck VRÖ with PID 3.

**Comment by icanos** [comment]
Have you gotten it to work?

**Comment by burymenot** [comment]
No I'm still stuck with the same problem. My log looks like this.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: Plejd
 Adds support for the Swedish home automation devices from Plejd.
-----------------------------------------------------------
 Add-on version: 0.4.5
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[09:33:33] ERROR: Unknown HTTP error occured
 System:   (amd64 / qemux86-64)
 Home Assistant version: 0.107.7
 Supervisor version: 209
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:33:33] INFO: Starting the Plejd service...
[09:33:33] INFO: Verified permissions on startup script
[09:33:33] INFO: Executing startup script
[09:33:33] INFO: Wrote plejd.json
[09:33:33] INFO: Running add-on
starting Plejd add-on v. 0.4.5
plejd-api: login()
plejd-api: logging into Svärdet
plejd-api: got session token response
plejd-api: getSites()
plejd-api: got site list response
plejd-api: getSite(...)
plejd-api: got site details response
wireEvents()
init()
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (DIM-01) named Vardagsrum Öv with PID 11.
plejd-mqtt: discovered light (DIM-02) named Taklampa with PID 14.
plejd-mqtt: discovered light (DIM-01) named Spegel with PID 15.
plejd-mqtt: discovered light (LED-10) named Smyg with PID 16.
plejd-mqtt: discovered light (DIM-02) named Spotlight with PID 13.
plejd-mqtt: discovered switch (Scene) named Tänd på min with PID 1.
plejd-mqtt: discovered switch (Scene) named Släck VRÖ with PID 3.
plejd-ble: connecting to /org/bluez/hci0/dev_CA_EC_AD_75_97_05
onDeviceConnected()
trying 10 characteristics
authenticate()
startPing()
startWriteQueue()
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (DIM-01) named Vardagsrum Öv with PID 11.
plejd-mqtt: discovered light (DIM-02) named Taklampa with PID 14.
plejd-mqtt: discovered light (DIM-01) named Spegel with PID 15.
plejd-mqtt: discovered light (LED-10) named Smyg with PID 16.
plejd-mqtt: discovered light (DIM-02) named Spotlight with PID 13.
plejd-mqtt: discovered switch (Scene) named Tänd på min with PID 1.
plejd-mqtt: discovered switch (Scene) named Släck VRÖ with PID 3.

**Comment by JoachimAndersson** [comment]
I had the same problem i had to remove MQTT integration and re-add it.

**Comment by icanos** [comment]
Closing due to inactivity
